export interface GameOption {
  text: string;
}

export interface GameQuestion {
  id: number;
  roadmapStage: string;
  category: "Choosing Branch / Stream" | "Course Duration" | "School Subjects" | "Skills to Build" | "College Degree & Exams" | "AI & Future World";
  categoryColor: string;
  question: string;
  options: GameOption[];
  correctIndex: number;
  explanation: string;
  proTip: string;
}

export interface CareerGame {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  badge: string;
  gradient: string;
  accentColor: string;
  description: string;
  totalQuestions: number;
  blueprintUrl: string;
  cheatSheet: string[];
  questions: GameQuestion[];
}

export const CAREER_GAMES: Record<string, CareerGame> = {
  swe: {
    id: "swe",
    title: "Software Engineer Roadmap Quiz",
    subtitle: "A student-friendly quiz for 8th, 9th & 10th classes: pick streams, course years, subjects & skills!",
    icon: "💻",
    badge: "For Classes 8th – 10th",
    gradient: "from-blue-600 via-indigo-600 to-violet-700",
    accentColor: "#6366F1",
    description: "Want to become a Software Engineer? Test if you know the exact roadmap: which stream to pick after Class 10, how many years each degree takes, which school subjects matter most, and what skills to build starting today!",
    totalQuestions: 10,
    blueprintUrl: "/career-reports?career=swe",
    cheatSheet: [
      "Class 8-10: Focus on Mathematics, logic puzzles, fast touch-typing & computer curiosity.",
      "After 10th: Choose MPC (Maths, Physics, Chemistry) for 2 years (or 3-year Polytechnic Diploma).",
      "After 12th: Prepare for JEE Main / State CET / EAPCET entrance exams.",
      "College Degree: 4-Year B.Tech / B.E. in Computer Science (or BCA + MCA).",
      "Future with AI: Use AI as a co-pilot while leading with human problem-solving & creative logic!"
    ],
    questions: [
      {
        id: 1,
        roadmapStage: "Stage 1: After 10th Class",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "When you pass Class 10, which Intermediate (10+2) stream should you select to become a Software Engineer in India?",
        options: [
          { text: "BiPC (Biology, Physics, Chemistry)" },
          { text: "MPC (Mathematics, Physics, Chemistry)" },
          { text: "CEC (Commerce, Economics, Civics)" },
          { text: "HEC (History, Economics, Civics)" },
        ],
        correctIndex: 1,
        explanation: "MPC (Mathematics, Physics, Chemistry) is the mandatory stream for appearing in engineering entrance exams like JEE Main, JEE Advanced, and State EAPCET / CET.",
        proTip: "If you like problem solving and Maths, MPC is your direct launchpad to Computer Science!",
      },
      {
        id: 2,
        roadmapStage: "Stage 2: Plus-Two Duration",
        category: "Course Duration",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "How many years does Intermediate (Junior College / Class 11 & 12) take to complete in India?",
        options: [
          { text: "1 Year" },
          { text: "4 Years" },
          { text: "2 Years (Class 11 & Class 12)" },
          { text: "6 Months" },
        ],
        correctIndex: 2,
        explanation: "Intermediate takes exactly 2 years (Class 11 and Class 12). During these 2 years, you prepare for both your Board exams and your Engineering entrance exams.",
        proTip: "Consistent daily study in Class 11 makes Class 12 board and entrance exams much less stressful.",
      },
      {
        id: 3,
        roadmapStage: "Stage 3: The Polytechnic Route",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "If you want a practical, low-cost route directly after Class 10 without studying Class 11-12, what option is available?",
        options: [
          { text: "A 1-month mobile phone screen repair course" },
          { text: "Direct admission into MBBS without Class 12" },
          { text: "Drop out and wait until age 21" },
          { text: "3-Year Polytechnic Diploma in Computer Engineering (via POLYCET)" },
        ],
        correctIndex: 3,
        explanation: "Polytechnic Diploma in Computer Engineering (after Class 10 via POLYCET) is a 3-year course. It gives hands-on computer skills and lets you enter directly into the 2nd year of B.Tech through ECET (Lateral Entry)!",
        proTip: "Polytechnic is an amazing low-cost option for students who want direct technical learning right after 10th.",
      },
      {
        id: 4,
        roadmapStage: "Stage 4: School Foundations",
        category: "School Subjects",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "Which subject that you are studying right now in 8th, 9th, or 10th is the MOST important foundation for software programming?",
        options: [
          { text: "Mathematics (Algebra, Arithmetic & Geometry)" },
          { text: "Ancient History of Egyptian Pharaohs" },
          { text: "Sanskrit Grammar" },
          { text: "Drawing & Watercolours" },
        ],
        correctIndex: 0,
        explanation: "Mathematics is the backbone of computer science! Coding is not about memorizing words; it's about breaking down problems step-by-step using mathematical and logical thinking.",
        proTip: "Don't just memorize math formulas — try to understand the 'why' behind each step.",
      },
      {
        id: 5,
        roadmapStage: "Stage 5: College Degree",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "After completing Class 12 (MPC), which undergraduate college degree is the main degree to become a professional Software Engineer?",
        options: [
          { text: "MBBS (Bachelor of Medicine)" },
          { text: "B.Tech / B.E. in Computer Science & Engineering (CSE)" },
          { text: "B.A. in History & Literature" },
          { text: "B.Com in General Accountancy" },
        ],
        correctIndex: 1,
        explanation: "B.Tech (Bachelor of Technology) or B.E. (Bachelor of Engineering) in CSE / IT is the prime degree. Other great degree pathways include BCA (Bachelor of Computer Applications) and B.Sc Computer Science.",
        proTip: "B.Tech CSE is the most sought-after degree for campus placements in software companies.",
      },
      {
        id: 6,
        roadmapStage: "Stage 6: Degree Duration",
        category: "Course Duration",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "How many years does a full-time B.Tech Engineering Degree take in India?",
        options: [
          { text: "2 Years" },
          { text: "1 Year" },
          { text: "4 Years (8 Semesters)" },
          { text: "6 Years" },
        ],
        correctIndex: 2,
        explanation: "A standard B.Tech degree takes 4 years (2 semesters per year = 8 semesters). During these 4 years, you learn computer languages, software design, and do internships.",
        proTip: "Students who do a 3-year Polytechnic Diploma get lateral entry into the 2nd year of B.Tech, completing B.Tech in 3 years!",
      },
      {
        id: 7,
        roadmapStage: "Stage 7: Skills to Build in School",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "As an 8th, 9th, or 10th student, what skills should you start building right now to prepare for this career?",
        options: [
          { text: "Memorising entire dictionaries without understanding" },
          { text: "Lifting heavy dumbbells and marathon running" },
          { text: "Playing mobile games for 8 hours every day" },
          { text: "Fast keyboard typing, logical puzzles (Sudoku/chess), and basic computer curiosity" },
        ],
        correctIndex: 3,
        explanation: "In high school, you don't need to be a coding master! Building fast touch-typing, playing logic games like chess or Sudoku, learning basic computer skills, and being curious about how apps work is the best foundation.",
        proTip: "Practice touch-typing for 15 minutes a day — it will make you 3x faster when you learn to code!",
      },
      {
        id: 8,
        roadmapStage: "Stage 8: Key Entrance Exams",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "Which entrance examination is written in India after Class 12 to get admission into top engineering colleges like IITs, NITs, and State Universities?",
        options: [
          { text: "JEE Main / JEE Advanced & State EAPCET / CET" },
          { text: "NEET (National Eligibility cum Entrance Test)" },
          { text: "CLAT (Common Law Admission Test)" },
          { text: "CA Foundation" },
        ],
        correctIndex: 0,
        explanation: "JEE Main and JEE Advanced are the premier national engineering exams for IITs and NITs. Every Indian state also conducts its own CET (like AP/TS EAPCET, KCET, MHT-CET) for state university admissions.",
        proTip: "Focus on understanding Class 11 and 12 Maths and Physics concepts thoroughly to crack these exams.",
      },
      {
        id: 9,
        roadmapStage: "Stage 9: What Engineers Actually Do",
        category: "Skills to Build",
        categoryColor: "bg-teal-100 text-teal-900 border-teal-300",
        question: "What does a Software Engineer actually do during their daily job?",
        options: [
          { text: "Repairs physical ceiling fans and electric wiring in homes" },
          { text: "Creates and maintains software apps like YouTube, WhatsApp, school portals, and games" },
          { text: "Sells mouse pads and keyboards in a street shop" },
          { text: "Only types letters in Microsoft Word all day" },
        ],
        correctIndex: 1,
        explanation: "Software engineers write instructions that tell computers and phones what to do. They build the games you play, the apps you order food with, Google Maps, online banking, and hospital systems!",
        proTip: "Every company in the world — from hospitals to banks and space agencies — needs software engineers.",
      },
      {
        id: 10,
        roadmapStage: "Stage 10: The Future with AI",
        category: "AI & Future World",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "By the time you finish school and graduate from college (in ~8 to 10 years), how will Artificial Intelligence (AI) shape software engineering?",
        options: [
          { text: "Computers will be thrown away and people will only use paper and ink" },
          { text: "Software will stop existing completely" },
          { text: "AI will help write simple code, so engineers who have creative ideas and solve real human problems will be super valuable!" },
          { text: "You won't need to study or learn anything ever again" },
        ],
        correctIndex: 2,
        explanation: "AI is a powerful super-assistant! It helps engineers build apps faster, but AI cannot replace human creativity, empathy, and problem solving. Future software engineers will be directors using AI tools to build big dreams!",
        proTip: "Students who cultivate strong thinking skills and learn how to collaborate with AI will have the highest-paying careers.",
      },
    ],
  },

  doctor: {
    id: "doctor",
    title: "Doctor & Healthcare Roadmap Quiz",
    subtitle: "A student-friendly quiz for 8th, 9th & 10th classes: BiPC stream, NEET, MBBS years, and healing lives!",
    icon: "🩺",
    badge: "For Classes 8th – 10th",
    gradient: "from-emerald-600 via-teal-600 to-cyan-700",
    accentColor: "#059669",
    description: "Dream of wearing the white coat and saving lives? Explore the real medical roadmap: which stream to choose after 10th, how many years MBBS takes, the truth about NEET, and what caring skills matter most!",
    totalQuestions: 10,
    blueprintUrl: "/career-reports?career=doctor",
    cheatSheet: [
      "Class 8-10: Build a solid foundation in Biology & Science, and develop patience and neat observation habits.",
      "After 10th: Choose BiPC (Biology, Physics, Chemistry) for 2 years of Intermediate / Junior College.",
      "After 12th: Appear for NEET-UG (National Eligibility cum Entrance Test).",
      "Medical College: 5.5 Years MBBS (4.5 years study + 1 year compulsory rotatory hospital internship).",
      "Plan B Options: BDS (Dental), BAMS (Ayurvedic), BHMS (Homeopathy), B.Sc Nursing, BPT Physiotherapy, or B.Pharm.",
      "Future with AI: AI will analyze MRI/X-ray scans in seconds, but doctor's empathy, bedside care, and human touch can never be automated!"
    ],
    questions: [
      {
        id: 1,
        roadmapStage: "Stage 1: After 10th Class",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "When you complete Class 10, which Intermediate (10+2) stream MUST you take to become a Doctor (MBBS) in India?",
        options: [
          { text: "MPC (Mathematics, Physics, Chemistry)" },
          { text: "BiPC (Biology, Physics, Chemistry)" },
          { text: "CEC (Commerce, Economics, Civics)" },
          { text: "MEC (Mathematics, Economics, Commerce)" },
        ],
        correctIndex: 1,
        explanation: "BiPC (Biology, Physics, Chemistry) is the compulsory stream. Biology (Botany and Zoology) carries 50% of the total marks in the medical entrance exam.",
        proTip: "If you love learning about the human body, plants, and living organisms, BiPC will feel natural and fascinating!",
      },
      {
        id: 2,
        roadmapStage: "Stage 2: School Foundations",
        category: "School Subjects",
        categoryColor: "bg-teal-100 text-teal-900 border-teal-300",
        question: "Which subject that you study in 8th, 9th, and 10th is the heart and soul of medical studies?",
        options: [
          { text: "General Science & Biology (Cells, Organ Systems & Living Processes)" },
          { text: "World Geography and Map Drawing" },
          { text: "Computer Coding in Python" },
          { text: "Accounting & Taxation" },
        ],
        correctIndex: 0,
        explanation: "Biology and Life Sciences form the bedrock of medicine. Learning how organs, the circulatory system, digestion, and cells function in school gives you a massive head start for MBBS.",
        proTip: "Draw neat biological diagrams in your school notebook — diagram memory helps tremendously in NEET!",
      },
      {
        id: 3,
        roadmapStage: "Stage 3: Plus-Two Duration",
        category: "Course Duration",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "How many years do you spend in Intermediate (Class 11 and 12) preparing for medical entrance?",
        options: [
          { text: "1 Year" },
          { text: "3 Years" },
          { text: "2 Years (Class 11 & Class 12)" },
          { text: "5 Years" },
        ],
        correctIndex: 2,
        explanation: "Intermediate takes 2 years. In these 2 years, you master the NCERT syllabus for Physics, Chemistry, and Biology, which is tested in the NEET exam.",
        proTip: "NCERT textbooks in Biology are considered the 'Bible' for NEET aspirants. Master them line by line!",
      },
      {
        id: 4,
        roadmapStage: "Stage 4: Mandatory Entrance Exam",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "Which single all-India entrance exam must every student write to enter medical college for MBBS or BDS in India?",
        options: [
          { text: "JEE Advanced" },
          { text: "UPSC Civil Services Exam" },
          { text: "CA Foundation" },
          { text: "NEET-UG (National Eligibility cum Entrance Test)" },
        ],
        correctIndex: 3,
        explanation: "NEET-UG is the sole entrance exam in India for admission into all government and private medical colleges (including AIIMS and JIPMER).",
        proTip: "Consistent daily revision of formulas and biology definitions is the key to cracking NEET.",
      },
      {
        id: 5,
        roadmapStage: "Stage 5: The Primary Medical Degree",
        category: "College Degree & Exams",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "What is the official name of the primary undergraduate bachelor degree required to practice modern medicine as a Doctor?",
        options: [
          { text: "B.Tech in Biomedical Engineering" },
          { text: "MBBS (Bachelor of Medicine and Bachelor of Surgery)" },
          { text: "B.Pharmacy" },
          { text: "B.Sc in Agriculture" },
        ],
        correctIndex: 1,
        explanation: "MBBS stands for Bachelor of Medicine and Bachelor of Surgery (from Latin: Medicinae Baccalaureus, Baccalaureus Chirurgiae). It grants you the legal license to treat patients.",
        proTip: "After passing MBBS and registering with the National Medical Commission (NMC), you earn the proud title 'Dr.' before your name!",
      },
      {
        id: 6,
        roadmapStage: "Stage 6: Medical Degree Duration",
        category: "Course Duration",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "How long does the complete MBBS course take from day one until you receive your doctor license?",
        options: [
          { text: "3 Years" },
          { text: "4 Years" },
          { text: "5.5 Years (4.5 Years College + 1 Year Hospital Internship)" },
          { text: "8 Years" },
        ],
        correctIndex: 2,
        explanation: "MBBS takes 5.5 years: 4.5 years of rigorous classroom, lab, and hospital ward training, followed by 1 full year of compulsory rotatory internship in a hospital treating real patients.",
        proTip: "The 1-year internship is where medical graduates work in surgery, medicine, pediatric, and emergency departments 24/7.",
      },
      {
        id: 7,
        roadmapStage: "Stage 7: Plan B Healthcare Options",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "NEET is highly competitive. If a BiPC student does not get an MBBS government seat, which rewarding alternative healthcare careers are available?",
        options: [
          { text: "BDS (Dentist), BAMS (Ayurveda), BPT (Physiotherapy), B.Sc Nursing, or B.Pharm" },
          { text: "There are zero other options in healthcare" },
          { text: "Only a factory worker job" },
          { text: "Waiting at home for 10 years" },
        ],
        correctIndex: 0,
        explanation: "Healthcare has dozens of noble, high-paying career paths! Dentists (BDS), Physiotherapists (BPT), Ayurvedic doctors (BAMS), Pharmacists, and specialized Nurses are in huge demand globally.",
        proTip: "Always keep a strong Plan B in mind — saving lives happens across the entire healthcare ecosystem!",
      },
      {
        id: 8,
        roadmapStage: "Stage 8: Skills to Build in School",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "What personal quality or skill should an 8th-10th student cultivate if they want to be a respected doctor?",
        options: [
          { text: "Getting angry quickly when things go wrong" },
          { text: "Disliking talking to people and staying isolated" },
          { text: "Only caring about buying expensive sports cars" },
          { text: "Empathy, patient listening, sharp observation, and calm focus under stress" },
        ],
        correctIndex: 3,
        explanation: "A patient visits a doctor when they are in pain or scared. Empathy (caring for others), listening carefully to symptoms, and remaining calm in emergencies make a truly great doctor.",
        proTip: "Practice listening to friends and family without interrupting them — good listening is half the diagnosis!",
      },
      {
        id: 9,
        roadmapStage: "Stage 9: Becoming a Specialist",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "After MBBS, if a doctor wants to specialize as a Cardiologist (Heart), Neurologist (Brain), or Surgeon, what postgraduate degree do they pursue?",
        options: [
          { text: "B.Ed (Bachelor of Education)" },
          { text: "MD (Doctor of Medicine) or MS (Master of Surgery) - 3 Years" },
          { text: "MBA in Marketing" },
          { text: "LLB (Bachelor of Law)" },
        ],
        correctIndex: 1,
        explanation: "After MBBS, doctors write the NEET-PG exam to enter 3-year MD (Medicine) or MS (Surgery) courses to become specialists in cardiology, pediatrics, orthopedics, or oncology.",
        proTip: "Specialization takes 3 additional years, but makes you an expert in your chosen field of healing.",
      },
      {
        id: 10,
        roadmapStage: "Stage 10: The Future with AI",
        category: "AI & Future World",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "How will Artificial Intelligence (AI) transform medicine by the time you become a doctor in 10-12 years?",
        options: [
          { text: "Robots will replace all human doctors and hospitals will have no people" },
          { text: "Diseases will completely stop existing in the world" },
          { text: "AI will analyze scans and predict illnesses early, but human doctors will provide the caring touch, judgment, and emotional comfort patients need" },
          { text: "Doctors will no longer need stethoscopes or medicines" },
        ],
        correctIndex: 2,
        explanation: "AI is becoming a powerful doctor's assistant — scanning X-rays in 2 seconds and discovering new medicines. However, a computer can never hold a crying patient's hand or deliver compassionate human reassurance.",
        proTip: "Future doctors who understand both medicine and AI tools will be the most sought-after healthcare leaders!",
      },
    ],
  },

  police: {
    id: "police",
    title: "Police Officer & IPS Roadmap Quiz",
    subtitle: "A student-friendly quiz for 8th, 9th & 10th classes: physical fitness, degrees, UPSC IPS, and protecting the nation!",
    icon: "👮",
    badge: "For Classes 8th – 10th",
    gradient: "from-amber-600 via-orange-600 to-red-700",
    accentColor: "#D97706",
    description: "Want to wear the Khaki uniform with proud stars and protect citizens? Discover the real roadmap: which streams qualify, how physical fitness tests work, how to crack SI and IPS exams, and what courage is all about!",
    totalQuestions: 10,
    blueprintUrl: "/career-reports?career=police",
    cheatSheet: [
      "Class 8-10: Build physical stamina (running, sports, NCC), follow daily news, and study Civics & Constitution.",
      "After 10th: Any stream! (MPC, BiPC, CEC, MEC, or Arts) — all are 100% eligible for police careers.",
      "College Degree: Complete any 3-year or 4-year Bachelor's degree (B.A., B.Sc., B.Com., or B.Tech).",
      "Two Main Pathways: 1) State Police Sub-Inspector (SI) via State Police Exam; 2) IPS Officer via UPSC Civil Services Exam.",
      "Academy Training: IPS officers train at the prestigious National Police Academy (SVPNPA) in Hyderabad.",
      "Future with AI: Modern policing uses AI for cyber-crime tracking, CCTV face recognition, and crime mapping, while human courage safeguards justice!"
    ],
    questions: [
      {
        id: 1,
        roadmapStage: "Stage 1: Stream Selection after 10th",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "Which stream should you select in Intermediate (Class 11 & 12) if your dream is to become a Police Sub-Inspector or an IPS Officer?",
        options: [
          { text: "Only MPC is allowed, other streams are banned" },
          { text: "Only Commerce CEC is accepted" },
          { text: "Any stream! (MPC, BiPC, CEC, MEC, or Arts) — all are 100% eligible!" },
          { text: "You must skip Intermediate and join the army" },
        ],
        correctIndex: 2,
        explanation: "There is no stream restriction for police forces or civil services! Whether you choose Arts, Science, or Commerce, you can become an IPS officer or Sub-Inspector as long as you complete your graduation.",
        proTip: "Pick the stream you genuinely enjoy in 11th and 12th so you can score high marks!",
      },
      {
        id: 2,
        roadmapStage: "Stage 2: The Top Police Rank (IPS)",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "What is the highest prestigious police exam in India conducted to select Indian Police Service (IPS) officers like SPs and DIGs?",
        options: [
          { text: "NEET Exam" },
          { text: "UPSC Civil Services Examination (CSE)" },
          { text: "JEE Advanced" },
          { text: "State Board 10th Class Exam" },
        ],
        correctIndex: 1,
        explanation: "UPSC (Union Public Service Commission) conducts the Civil Services Exam every year. Top rankers who choose police service are appointed as IPS officers (starting as ASP / SP).",
        proTip: "Reading newspapers like The Hindu or Indian Express from high school gives you deep general knowledge for UPSC.",
      },
      {
        id: 3,
        roadmapStage: "Stage 3: Sub-Inspector (SI) Route",
        category: "College Degree & Exams",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "If you want to join your state police as a Sub-Inspector (SI) leading a local police station, who conducts that recruitment?",
        options: [
          { text: "State Police Recruitment Board (SLPRB) through SI Written & Physical Tests" },
          { text: "School principal interviews" },
          { text: "A lucky lottery draw" },
          { text: "Local municipality sports club" },
        ],
        correctIndex: 0,
        explanation: "Each state government has a State Level Police Recruitment Board that conducts SI examinations consisting of a prelims exam, physical endurance test (PET), and mains exam.",
        proTip: "SI is one of the most respected direct-entry leadership posts in state law enforcement.",
      },
      {
        id: 4,
        roadmapStage: "Stage 4: Physical Fitness in School",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "Unlike many desk jobs, police recruitment includes strict Physical Fitness Tests. What should high school students start practicing now?",
        options: [
          { text: "Sitting on a sofa playing video games all evening" },
          { text: "Eating junk food every day to gain weight" },
          { text: "Sleeping 14 hours a day" },
          { text: "Running endurance (1600m / 800m), long jump, push-ups, sports, and school NCC/scouts" },
        ],
        correctIndex: 3,
        explanation: "Every police selection has a Physical Efficiency Test (PET) that tests running (e.g. 1600 meters in ~7 minutes), long jump, and height/chest standards. Joining NCC or playing sports in school builds this naturally.",
        proTip: "Join NCC (National Cadet Corps) in school or junior college — 'C' certificate holders get special bonus weightage!",
      },
      {
        id: 5,
        roadmapStage: "Stage 5: High School Subjects",
        category: "School Subjects",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "Which subject you study right now in 8th, 9th, or 10th directly relates to laws, government, and the Indian Constitution?",
        options: [
          { text: "Chemistry laboratory titration" },
          { text: "Social Studies (Civics, Indian Constitution, History & Geography)" },
          { text: "Trigonometry and Calculus" },
          { text: "Botany flower dissection" },
        ],
        correctIndex: 1,
        explanation: "Social Studies — especially Civics and the Indian Constitution — teaches Fundamental Rights, duties, the judiciary, and how the state machinery operates. This forms 60% of General Studies in police exams!",
        proTip: "Pay close attention to your Civics lessons on the Parliament, Supreme Court, and Fundamental Rights.",
      },
      {
        id: 6,
        roadmapStage: "Stage 6: College Degree Requirement",
        category: "Course Duration",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "To be eligible to appear for the UPSC IPS exam or State Police Sub-Inspector (SI) exam, what minimum education is legally required?",
        options: [
          { text: "Only 5th Class pass" },
          { text: "Only 10th Class certificate" },
          { text: "Any recognized Bachelor's Degree (3 or 4 Years) from a university" },
          { text: "A Ph.D. Doctorate Degree (10 years)" },
        ],
        correctIndex: 2,
        explanation: "Candidates must hold any recognized undergraduate bachelor degree (like B.A., B.Sc., B.Com., or B.Tech). Even students in their final year of college can apply for UPSC CSE prelims!",
        proTip: "Maintain a steady 60%+ average in your degree so you meet all state and national eligibility criteria.",
      },
      {
        id: 7,
        roadmapStage: "Stage 7: The National Police Academy",
        category: "College Degree & Exams",
        categoryColor: "bg-teal-100 text-teal-900 border-teal-300",
        question: "Where in India are newly selected IPS officers trained in weapon handling, forensic science, horse riding, and criminal law?",
        options: [
          { text: "Sardar Vallabhbhai Patel National Police Academy (SVPNPA) in Hyderabad" },
          { text: "A movie theater in Mumbai" },
          { text: "A private coaching centre in Delhi" },
          { text: "At home through Zoom calls" },
        ],
        correctIndex: 0,
        explanation: "The Sardar Vallabhbhai Patel National Police Academy (SVPNPA) in Hyderabad is India's world-famous premier training academy where IPS probationers undergo intensive 1-year training.",
        proTip: "SVPNPA is known as the 'Cradle of Police Leadership' in India.",
      },
      {
        id: 8,
        roadmapStage: "Stage 8: Personality & Mental Strength",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "Beyond muscles and physical strength, what is the most vital mental quality a good police officer must possess?",
        options: [
          { text: "Taking bribes and breaking rules" },
          { text: "Showing off on social media with sunglasses" },
          { text: "Being cruel to poor or weak citizens" },
          { text: "High honesty, emotional calm under public pressure, courage, and respect for human dignity" },
        ],
        correctIndex: 3,
        explanation: "A true officer is a protector of citizens. Mental courage, honesty (integrity), staying calm during public tensions, and treating every citizen with equal fairness are the real qualities of heroism.",
        proTip: "Stand up for fairness and honesty in your school classroom — leadership begins with small everyday acts!",
      },
      {
        id: 9,
        roadmapStage: "Stage 9: Everyday Role & Duty",
        category: "Skills to Build",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "What is the primary daily mission of police officers in our society?",
        options: [
          { text: "Constructing highways and bridges" },
          { text: "Preventing crimes, maintaining peace, safeguarding citizens, and helping people in emergencies" },
          { text: "Selling airline flight tickets" },
          { text: "Repairing computer motherboards" },
        ],
        correctIndex: 1,
        explanation: "Police officers are the frontline guardians of law and order. They protect women and children, investigate theft and cybercrimes, manage emergency rescues, and maintain social harmony.",
        proTip: "Police officers are available 24 hours a day, 365 days a year to keep our cities and villages safe.",
      },
      {
        id: 10,
        roadmapStage: "Stage 10: Future Policing with AI",
        category: "AI & Future World",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "How will Artificial Intelligence (AI) and technology assist police officers over the next 10 years?",
        options: [
          { text: "Robo-cops will arrest people without any trials or courts" },
          { text: "Crimes will disappear forever with zero effort" },
          { text: "Smart AI systems will help detect cyber financial frauds, monitor smart traffic cameras, and map crime hotspots, while human officers ensure fairness and justice" },
          { text: "Police uniforms will be discontinued" },
        ],
        correctIndex: 2,
        explanation: "AI empowers modern police forces with predictive crime mapping, high-speed cyber forensic tracking, and automatic traffic management. Human empathy, constitutional judgment, and ground bravery remain irreplaceable.",
        proTip: "Learning basic computer security and cyber hygiene in school will make you a smart, modern law enforcement candidate!",
      },
    ],
  },

  teacher: {
    id: "teacher",
    title: "Teacher & Educator Roadmap Quiz",
    subtitle: "A student-friendly quiz for 8th, 9th & 10th classes: subject mastery, B.Ed degree, TET exams, and shaping future generations!",
    icon: "👩‍🏫",
    badge: "For Classes 8th – 10th",
    gradient: "from-sky-600 via-blue-600 to-indigo-700",
    accentColor: "#0284C7",
    description: "Want to follow in the footsteps of Dr. Sarvepalli Radhakrishnan or APJ Abdul Kalam and inspire young minds? Learn the exact roadmap: stream choices, B.Ed vs D.El.Ed, TET exams, and skills needed to become a master educator!",
    totalQuestions: 10,
    blueprintUrl: "/career-reports?career=teacher",
    cheatSheet: [
      "Class 8-10: Fall in love with your favorite subject, practice explaining topics to friends, and build clear public speaking.",
      "After 10th: Pick the stream that matches what you want to teach (MPC for Maths/Physics, BiPC for Biology, CEC/HEC for Social Sciences/Languages).",
      "Teacher Training Paths: 1) D.El.Ed (2-year diploma after 12th for Primary school); 2) Graduation + B.Ed (2-year degree for High School); 3) Post-Graduation + NET/Ph.D. for College Professor.",
      "Key Exams: CTET (Central Teacher Eligibility Test) & State TET for government and top private schools.",
      "Future with AI: AI helps create lesson plans and grade tests, but great teachers spark curiosity, build character, and inspire human potential!"
    ],
    questions: [
      {
        id: 1,
        roadmapStage: "Stage 1: Choosing Stream after 10th",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "Which stream should you choose in Intermediate (10+2) if you want to become a Teacher?",
        options: [
          { text: "There is only one single stream for all teachers in India" },
          { text: "Choose the stream related to the subject you love most! (MPC for Maths/Physics, BiPC for Biology, CEC/HEC for Social Studies or Languages)" },
          { text: "You can only become a teacher if you fail all exams" },
          { text: "Only engineering streams are permitted" },
        ],
        correctIndex: 1,
        explanation: "Teaching depends on your subject passion! If you want to teach Mathematics, take MPC. If you love Biology, take BiPC. If you love History or Economics, choose HEC or CEC. Language teachers can pick any stream!",
        proTip: "Ask yourself: Which subject do you enjoy explaining to your classmates the most?",
      },
      {
        id: 2,
        roadmapStage: "Stage 2: The Core Teaching Degree",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "What is the standard professional degree in India required to become a High School Teacher (Classes 6 to 10)?",
        options: [
          { text: "B.Ed (Bachelor of Education) taken after graduation (or integrated 4-year ITEP)" },
          { text: "B.Com in General Auditing" },
          { text: "MBBS Degree" },
          { text: "Diploma in Hotel Cooking" },
        ],
        correctIndex: 0,
        explanation: "B.Ed (Bachelor of Education) is the gold standard teacher training degree in India. It teaches child psychology, modern teaching methods, lesson planning, and classroom management.",
        proTip: "National Education Policy (NEP) also offers 4-year integrated B.Sc-B.Ed or B.A-B.Ed right after Class 12!",
      },
      {
        id: 3,
        roadmapStage: "Stage 3: Primary School Pathway",
        category: "Course Duration",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "If someone wants to teach young primary children (Classes 1 to 5) directly after Class 12, what 2-year diploma course is popular in India?",
        options: [
          { text: "6-Year Ph.D. Research" },
          { text: "A 2-day workshop on YouTube" },
          { text: "D.El.Ed (Diploma in Elementary Education / TTC) - 2 Years" },
          { text: "Commercial Pilot License" },
        ],
        correctIndex: 2,
        explanation: "D.El.Ed (Diploma in Elementary Education), earlier known as TTC (Teacher Training Certificate), is a 2-year diploma after 10+2 focused specifically on foundational early-childhood learning.",
        proTip: "Primary teachers have the magical privilege of teaching children how to read, write, and count for the first time!",
      },
      {
        id: 4,
        roadmapStage: "Stage 4: Key Teacher Eligibility Exams",
        category: "College Degree & Exams",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "Which nationwide examination must be cleared in India to qualify for teaching jobs in Kendriya Vidyalayas (KVS), Navodaya, and CBSE schools?",
        options: [
          { text: "NEET Medical Exam" },
          { text: "CAT MBA Exam" },
          { text: "Chartered Accountancy Final" },
          { text: "CTET (Central Teacher Eligibility Test) & State TET" },
        ],
        correctIndex: 3,
        explanation: "CTET (conducted by CBSE) and State TETs are mandatory qualification tests to ensure that all appointed school teachers meet high national pedagogy and subject standards.",
        proTip: "A CTET certificate is now valid for lifetime, making it an incredible asset for your career!",
      },
      {
        id: 5,
        roadmapStage: "Stage 5: High School Habits",
        category: "Skills to Build",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "What habit can you start practicing in 8th, 9th, or 10th class that naturally prepares you to be a master teacher?",
        options: [
          { text: "Hiding your notes and refusing to help classmates who are struggling" },
          { text: "Helping your friends understand tricky topics and practicing explaining concepts simply" },
          { text: "Interrupting teachers and disrupting the classroom" },
          { text: "Memorizing answers word-for-word without understanding the meaning" },
        ],
        correctIndex: 1,
        explanation: "The best way to learn is to teach! When you explain a math problem or science concept to a friend in your own simple words, you build clarity, patience, and communication skills.",
        proTip: "Form a study group with 2 friends and take turns teaching one chapter to each other each week!",
      },
      {
        id: 6,
        roadmapStage: "Stage 6: Standard B.Ed Duration",
        category: "Course Duration",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "How many years does the standard B.Ed degree course take in Indian universities after completing your Bachelor degree?",
        options: [
          { text: "6 Months" },
          { text: "5 Years" },
          { text: "2 Years (4 Semesters)" },
          { text: "10 Years" },
        ],
        correctIndex: 2,
        explanation: "The standard B.Ed course takes 2 years (divided into 4 semesters). It includes classroom training, internship in real schools, and practical teaching demonstrations.",
        proTip: "During B.Ed, you spend months doing practice teaching in real government or private classrooms.",
      },
      {
        id: 7,
        roadmapStage: "Stage 7: The College Professor Route",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "If you want to teach older college or university students as an Assistant Professor or Lecturer, what qualification is required?",
        options: [
          { text: "Master's Degree (M.A. / M.Sc. / M.Com) + Clearing UGC-NET (or Ph.D.)" },
          { text: "Only 10th Class pass with 50% marks" },
          { text: "Just knowing how to drive a car" },
          { text: "Winning a school running race" },
        ],
        correctIndex: 0,
        explanation: "To teach at the college and university level, you need a Master's degree (55%+ marks) followed by clearing the National Eligibility Test (UGC-NET / CSIR-NET) or completing a Ph.D. research doctorate.",
        proTip: "Professors both teach degree students and conduct original research to discover new knowledge for humanity.",
      },
      {
        id: 8,
        roadmapStage: "Stage 8: Core Skills of an Inspiring Educator",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "What is the most important personal quality of a truly memorable teacher?",
        options: [
          { text: "Carrying a big wooden stick and scaring students" },
          { text: "Never smiling and giving zero marks to everyone" },
          { text: "Reading lines monotonically from a textbook without explaining" },
          { text: "Patience, infectious passion for the subject, empathy for slow learners, and encouraging words" },
        ],
        correctIndex: 3,
        explanation: "Students never forget a teacher who believed in them! Great teachers make hard subjects fun, encourage students when they fail, and inspire lifelong curiosity and confidence.",
        proTip: "Think about your favorite teacher in school — it's always their patience and kindness that made learning fun!",
      },
      {
        id: 9,
        roadmapStage: "Stage 9: What Teachers Do Every Day",
        category: "Skills to Build",
        categoryColor: "bg-teal-100 text-teal-900 border-teal-300",
        question: "What does the day-to-day work of a dedicated teacher involve?",
        options: [
          { text: "Sitting quietly in an empty room with locked doors" },
          { text: "Designing engaging lessons, teaching students, checking homework, mentoring struggling learners, and organizing school activities" },
          { text: "Selling school uniforms in a clothing market" },
          { text: "Only working for 10 minutes a day" },
        ],
        correctIndex: 1,
        explanation: "Teaching is dynamic and full of life! Teachers create visual charts, explain concepts, mentor students through personal challenges, conduct science experiments, and shape future citizens.",
        proTip: "Teachers touch hundreds of lives every year — doctors, engineers, and presidents all learned from teachers first!",
      },
      {
        id: 10,
        roadmapStage: "Stage 10: Future Teaching with AI",
        category: "AI & Future World",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "With AI tools like ChatGPT and digital learning apps growing rapidly, what will happen to human teachers in the future?",
        options: [
          { text: "Schools will be completely abolished and children won't have any mentors" },
          { text: "AI will replace all human relationships" },
          { text: "AI will help teachers make interactive quizzes and lesson plans, while human teachers mentor students, build moral character, and inspire dreams!" },
          { text: "Students will be taught by mechanical factory machines" },
        ],
        correctIndex: 2,
        explanation: "AI can provide information, but it can never inspire a heart! Future teachers will use AI tools to automate paperwork and create exciting multimedia lessons, freeing up more time to mentor, guide, and care for each child individually.",
        proTip: "A teacher who embraces modern digital tools and leads with genuine human warmth is unbeatable in the AI era!",
      },
    ],
  },

  ias: {
    id: "ias",
    title: "IAS / Civil Services Roadmap Quiz",
    subtitle: "A student-friendly quiz for 8th, 9th & 10th classes: UPSC CSE, District Collector responsibilities, and public leadership!",
    icon: "🏛️",
    badge: "For Classes 8th – 10th",
    gradient: "from-amber-700 via-orange-700 to-yellow-800",
    accentColor: "#B45309",
    description: "Dream of leading a district as a District Collector and making policies that touch millions of citizens? Explore the real civil services roadmap: stream choices, degrees, UPSC exam stages, and leadership traits!",
    totalQuestions: 10,
    blueprintUrl: "/career-reports?career=ias",
    cheatSheet: [
      "Class 8-10: Read daily newspapers, build general awareness, and develop strong understanding of Civics & Indian History.",
      "After 10th: Any stream! (MPC, BiPC, CEC, MEC, or Arts/HEC) — all streams are 100% eligible for civil services.",
      "College Degree: Any 3-year or 4-year Bachelor's degree (B.A., B.Sc., B.Com., B.Tech, or MBBS).",
      "The Big Exam: UPSC Civil Services Examination (CSE) conducted in 3 stages: Prelims, Mains, and Personality Test (Interview).",
      "Academy Training: Selected IAS probationers train at LBSNAA (Mussoorie, Uttarakhand).",
      "Future with AI: AI will speed up file processing and public grievance handling, while ethical leadership and human justice stay firmly with civil servants!"
    ],
    questions: [
      {
        id: 1,
        roadmapStage: "Stage 1: Intermediate Stream Selection",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "Which stream should you pick in Class 11 and 12 (Intermediate) if you want to become an IAS Officer in the future?",
        options: [
          { text: "Only Arts (HEC) is permitted, all other streams are disqualified" },
          { text: "Any stream you like! (MPC, BiPC, CEC, MEC, or Arts) — all are 100% equally eligible for UPSC CSE!" },
          { text: "Only Science students can appear" },
          { text: "You cannot study Intermediate in India" },
        ],
        correctIndex: 1,
        explanation: "UPSC does not demand any specific stream! Thousands of successful IAS officers come from Arts, Science, Commerce, and Engineering backgrounds alike.",
        proTip: "Choose the stream you enjoy most in 11th and 12th so you build strong critical thinking and conceptual depth.",
      },
      {
        id: 2,
        roadmapStage: "Stage 2: Degree Requirement",
        category: "Course Duration",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "What minimum educational qualification is required by law to sit for the UPSC Civil Services Examination?",
        options: [
          { text: "A Ph.D. doctorate degree with 10 years experience" },
          { text: "Only a 12th Class board pass certificate" },
          { text: "Any recognized Bachelor's Degree (3 or 4 years) in any subject from an Indian university" },
          { text: "A specialized degree only from Oxford or Harvard" },
        ],
        correctIndex: 2,
        explanation: "Any graduate holding a recognized Bachelor's degree (such as B.A., B.Sc., B.Com., B.Tech, or MBBS) can appear. Even final-year college students can write the preliminary exam!",
        proTip: "Many aspirants complete graduation in B.A. Political Science/History or B.Tech before preparing for UPSC.",
      },
      {
        id: 3,
        roadmapStage: "Stage 3: The National Exam",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "Which premier constitutional body in India conducts the prestigious Civil Services Examination every year?",
        options: [
          { text: "UPSC (Union Public Service Commission)" },
          { text: "CBSE School Board" },
          { text: "National Testing Agency (NTA)" },
          { text: "State Police Recruitment Board" },
        ],
        correctIndex: 0,
        explanation: "The Union Public Service Commission (UPSC) is India's premier central recruiting agency that conducts the nationwide Civil Services Examination for IAS, IPS, IFS, and IRS.",
        proTip: "UPSC CSE is considered one of the most respected examinations in the entire world.",
      },
      {
        id: 4,
        roadmapStage: "Stage 4: The 3 Stages of UPSC",
        category: "College Degree & Exams",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "How is the UPSC Civil Services Examination structured from start to finish?",
        options: [
          { text: "Only a 100-meter sprint and push-up contest" },
          { text: "A single 30-minute online multiple-choice test" },
          { text: "A lucky draw system" },
          { text: "3 Stages: Prelims (Objective MCQs) -> Mains (9 Descriptive Written Papers) -> Personality Test (Interview)" },
        ],
        correctIndex: 3,
        explanation: "UPSC CSE has 3 rigorous stages: 1) Prelims tests broad knowledge, 2) Mains tests deep analytical written expression across 9 papers, and 3) Personality Test evaluates character, leadership, and integrity.",
        proTip: "Writing clear, structured essays and answers in Mains is what secures top ranks in UPSC!",
      },
      {
        id: 5,
        roadmapStage: "Stage 5: School Subjects Foundation",
        category: "School Subjects",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "Which subject that you study in 8th, 9th, or 10th forms the biggest foundation for General Studies in UPSC?",
        options: [
          { text: "Trigonometric calculus only" },
          { text: "Social Studies (Indian History, Geography, Civics/Polity & Economics)" },
          { text: "Chemistry laboratory titration" },
          { text: "Computer graphic animations" },
        ],
        correctIndex: 1,
        explanation: "Social Science is the heart of General Studies! NCERT textbooks from Class 6 to 10 in History, Geography, Polity, and Economics are the primary study material read by even adult UPSC toppers.",
        proTip: "Read your school Social Science NCERT books with genuine curiosity — you are already building your UPSC foundation!",
      },
      {
        id: 6,
        roadmapStage: "Stage 6: Real Role of an IAS Officer",
        category: "Skills to Build",
        categoryColor: "bg-teal-100 text-teal-900 border-teal-300",
        question: "What are the primary duties of an IAS Officer serving as a District Collector / District Magistrate?",
        options: [
          { text: "Repairing electric meters in houses" },
          { text: "Acting in television shows and movies" },
          { text: "Supervising district administration, implementing welfare schemes (food, water, roads, schools), and managing disaster relief" },
          { text: "Selling school textbooks in town markets" },
        ],
        correctIndex: 2,
        explanation: "A District Collector is the administrative captain of an entire district (often home to 15 to 30 lakh citizens). They oversee education, healthcare, law and order, flood/drought relief, and elections.",
        proTip: "Few careers in the world give you this much direct power to improve the lives of millions of underprivileged citizens.",
      },
      {
        id: 7,
        roadmapStage: "Stage 7: Habits to Build in School",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "What daily habit should a high school student cultivate to prepare for future administrative leadership?",
        options: [
          { text: "Watching short video reels for 5 hours every day" },
          { text: "Arguing angrily without listening to facts" },
          { text: "Never reading anything outside school textbooks" },
          { text: "Reading newspapers daily, staying curious about current affairs, and writing opinions clearly in simple language" },
        ],
        correctIndex: 3,
        explanation: "Developing a daily habit of reading quality newspapers (like The Hindu or Indian Express) and following national and international news builds broad perspective, vocabulary, and balanced thinking.",
        proTip: "Start by reading the editorial page and national news columns for just 20 minutes each morning.",
      },
      {
        id: 8,
        roadmapStage: "Stage 8: The Famous Training Academy",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "Where in India are newly appointed IAS probationers trained to become visionary administrators?",
        options: [
          { text: "LBSNAA (Lal Bahadur Shastri National Academy of Administration) in Mussoorie, Uttarakhand" },
          { text: "A cinema studio in Chennai" },
          { text: "A shopping mall in Delhi" },
          { text: "At home through social media videos" },
        ],
        correctIndex: 0,
        explanation: "LBSNAA in scenic Mussoorie is India's premier civil services academy. Officers undergo village visits, trekking, administrative law, public economics, and policy training here.",
        proTip: "Walking through the gates of LBSNAA is the lifelong dream of millions of youth across India.",
      },
      {
        id: 9,
        roadmapStage: "Stage 9: Minimum Age Requirement",
        category: "Course Duration",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "What is the minimum age required to appear for the UPSC Civil Services Examination?",
        options: [
          { text: "16 Years (right after 10th)" },
          { text: "21 Years (after completing graduation)" },
          { text: "35 Years" },
          { text: "18 Years (right after 12th)" },
        ],
        correctIndex: 1,
        explanation: "A candidate must have attained the age of 21 years on August 1 of the examination year and completed graduation to write UPSC CSE.",
        proTip: "Starting college graduation at age 18 allows you to appear for UPSC immediately upon turning 21!",
      },
      {
        id: 10,
        roadmapStage: "Stage 10: Governance in the AI Era",
        category: "AI & Future World",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "How will Artificial Intelligence (AI) transform public administration and the work of IAS officers in the next decade?",
        options: [
          { text: "AI will eliminate government entirely and citizens won't have laws" },
          { text: "AI will make human decision-making illegal" },
          { text: "AI will automate routine paperwork, predict drought/flood patterns, and track ration delivery, while IAS officers make compassionate, ethical human decisions for people" },
          { text: "All government offices will be closed forever" },
        ],
        correctIndex: 2,
        explanation: "AI will make government services fast and transparent — detecting fraud in welfare schemes and predicting crop failures. However, ethical empathy, crisis leadership, and constitutional justice require human wisdom.",
        proTip: "Future civil servants who harness data and AI to solve poverty and public health will create revolutionary impact!",
      },
    ],
  },

  nurse: {
    id: "nurse",
    title: "Nurse & Healthcare Roadmap Quiz",
    subtitle: "A student-friendly quiz for 8th, 9th & 10th classes: BiPC stream, B.Sc Nursing, patient care, and global opportunities!",
    icon: "💉",
    badge: "For Classes 8th – 10th",
    gradient: "from-teal-600 via-emerald-600 to-green-700",
    accentColor: "#0D9488",
    description: "Want to follow Florence Nightingale and be the heart of hospital healing? Learn the nursing roadmap: stream selection, B.Sc Nursing vs GNM, clinical training, and huge worldwide career demand!",
    totalQuestions: 10,
    blueprintUrl: "/career-reports?career=nurse",
    cheatSheet: [
      "Class 8-10: Master Biology and Science basics, and cultivate deep kindness, patience, and attention to detail.",
      "After 10th: Choose BiPC (Biology, Physics, Chemistry) for 2 years of Intermediate / Junior College.",
      "Two Main Pathways: 1) 4-Year B.Sc Nursing degree (via state/national entrance); 2) 3-Year GNM diploma.",
      "Hands-On Training: Real hospital ward internships covering emergency, pediatric, ICU, and surgical wards.",
      "Global Demand: Indian nursing graduates have extraordinary international employment opportunities in the UK, USA, Canada, Australia, and Middle East.",
      "Future with AI: Smart sensors and AI will track patient vitals automatically, but comforting bedside care and empathetic healing are 100% human!"
    ],
    questions: [
      {
        id: 1,
        roadmapStage: "Stage 1: Stream Selection after 10th",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "Which stream should you choose in Intermediate (Class 11 and 12) to pursue a professional B.Sc Nursing degree?",
        options: [
          { text: "CEC (Commerce, Economics, Civics)" },
          { text: "BiPC (Biology, Physics, Chemistry)" },
          { text: "HEC (History, Economics, Civics)" },
          { text: "Fine Arts & Classical Music" },
        ],
        correctIndex: 1,
        explanation: "BiPC (Biology, Physics, Chemistry) is required for admission into B.Sc Nursing programs across Indian universities and healthcare institutes.",
        proTip: "Biology is the most crucial subject, especially understanding human organs, cells, and nutrition.",
      },
      {
        id: 2,
        roadmapStage: "Stage 2: Primary Professional Degree",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "What is the primary four-year undergraduate degree in India for practicing as a registered professional Nurse?",
        options: [
          { text: "B.Sc Nursing (Bachelor of Science in Nursing)" },
          { text: "B.Com in Banking" },
          { text: "B.Tech in Chemical Engineering" },
          { text: "Diploma in Hotel Front Desk" },
        ],
        correctIndex: 0,
        explanation: "B.Sc Nursing is a 4-year degree recognized by the Indian Nursing Council (INC) that prepares graduates for clinical nursing, critical care, and healthcare administration.",
        proTip: "B.Sc Nursing graduates qualify for exciting roles in top hospitals as well as direct opportunities abroad.",
      },
      {
        id: 3,
        roadmapStage: "Stage 3: B.Sc Nursing Course Duration",
        category: "Course Duration",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "How many years does a full-time B.Sc Nursing degree take in Indian medical and nursing colleges?",
        options: [
          { text: "1 Year" },
          { text: "2 Years" },
          { text: "4 Years (including clinical hospital ward training)" },
          { text: "7 Years" },
        ],
        correctIndex: 2,
        explanation: "B.Sc Nursing takes 4 years. It combines medical classroom theory (anatomy, physiology, pharmacology) with extensive hands-on clinical training in hospital wards.",
        proTip: "During these 4 years, student nurses rotate through maternity, pediatric, psychiatric, and emergency departments.",
      },
      {
        id: 4,
        roadmapStage: "Stage 4: Diploma Route (GNM)",
        category: "Course Duration",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "What is the alternative 3-year diploma course in nursing popular after Class 12?",
        options: [
          { text: "A 2-week fitness trainer certificate" },
          { text: "Direct PhD in Surgery" },
          { text: "Commercial Driving License" },
          { text: "GNM (General Nursing and Midwifery) - 3 Years" },
        ],
        correctIndex: 3,
        explanation: "GNM (General Nursing and Midwifery) is a 3-year diploma course. After completing GNM and getting registered, students can also pursue a 2-year Post-Basic B.Sc Nursing to upgrade to a degree!",
        proTip: "GNM is a faster, cost-effective route to enter the healthcare workforce quickly.",
      },
      {
        id: 5,
        roadmapStage: "Stage 5: High School Foundation",
        category: "School Subjects",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "Which subject in school right now teaches you about germs, bacteria, hygiene, and human body organs?",
        options: [
          { text: "Ancient Roman History" },
          { text: "Science & Biology (Health, Hygiene, Microorganisms & Organ Systems)" },
          { text: "Geometry and Theorems" },
          { text: "Sanskrit Grammar" },
        ],
        correctIndex: 1,
        explanation: "School Science and Biology lessons on microorganisms, disease transmission, immunity, and bodily organs provide the core foundation for medical nursing.",
        proTip: "Good hand hygiene and understanding how infections spread starts right in your school science class!",
      },
      {
        id: 6,
        roadmapStage: "Stage 6: Qualities of a Compassionate Nurse",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "What personal qualities and skills are most essential for a nurse working in emergency and hospital wards?",
        options: [
          { text: "Being loud and impatient with sick people" },
          { text: "Panicking whenever there is an emergency" },
          { text: "Refusing to help patients who cannot walk" },
          { text: "Kindness, emotional empathy, physical stamina, patience, and sharp observation of patient vitals" },
        ],
        correctIndex: 3,
        explanation: "Nurses spend more continuous time with patients than any other medical professional! Kindness, comforting words, quick attention to changes in health, and physical stamina make nursing a noble calling.",
        proTip: "Developing gentle communication and calm patience with your family is great practice for a caring career.",
      },
      {
        id: 7,
        roadmapStage: "Stage 7: What Nurses Do Daily",
        category: "Skills to Build",
        categoryColor: "bg-teal-100 text-teal-900 border-teal-300",
        question: "What are the essential daily responsibilities of a staff nurse in a modern hospital?",
        options: [
          { text: "Administering medications, checking vitals (BP, pulse, oxygen), assisting doctors in surgeries, and comforting recovering patients" },
          { text: "Cooking meals for the entire hospital cafeteria" },
          { text: "Repairing ambulances and hospital electrical generators" },
          { text: "Selling medicines at retail prices in town" },
        ],
        correctIndex: 0,
        explanation: "Nurses are on the frontline 24/7! They administer IV lines and injections, monitor cardiac monitors, dress wounds, assist surgeons in the operation theater, and help patients recover.",
        proTip: "In many critical care units, nurses are the first to detect medical emergencies and save patients' lives.",
      },
      {
        id: 8,
        roadmapStage: "Stage 8: Worldwide Global Opportunities",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "Why is Nursing considered one of the highest-demand careers internationally for Indian graduates?",
        options: [
          { text: "Hospitals in foreign countries are completely closing down" },
          { text: "Indian nurses are world-renowned for their high clinical competence and care, with massive demand and high salaries in the UK, USA, Canada, Australia, and Gulf nations" },
          { text: "Foreign countries do not allow doctors or nurses" },
          { text: "Nursing is only allowed in one city in India" },
        ],
        correctIndex: 1,
        explanation: "There is an enormous global shortage of healthcare workers. Passing language tests (IELTS/OET) and licensing exams (like NCLEX-RN for the USA) opens doors to high-paying international nursing careers.",
        proTip: "Learning strong English communication in school gives you a major advantage for global nursing exams!",
      },
      {
        id: 9,
        roadmapStage: "Stage 9: Higher Specialisations",
        category: "College Degree & Exams",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "After completing B.Sc Nursing, what postgraduate degree allows nurses to become specialists, nursing superintendents, or professors?",
        options: [
          { text: "LLB Degree" },
          { text: "B.Com" },
          { text: "M.Sc Nursing (Master of Science in Nursing) - 2 Years" },
          { text: "Diploma in Acting" },
        ],
        correctIndex: 2,
        explanation: "M.Sc Nursing (2 years) allows specialization in Cardiology, Pediatrics, Obstetrics, Psychiatry, or Community Health, leading to leadership and teaching roles.",
        proTip: "Nursing superintendents and nurse researchers command tremendous respect in healthcare administration.",
      },
      {
        id: 10,
        roadmapStage: "Stage 10: Future of Nursing in the AI Era",
        category: "AI & Future World",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "With smart patient monitors and AI alert systems in hospitals, what role will nurses play in the future?",
        options: [
          { text: "Robots will provide all emotional comfort and human nurses will disappear" },
          { text: "Hospitals will no longer have patients" },
          { text: "AI will track vitals and alert sudden changes in seconds, while nurses provide the compassionate human care, emotional comfort, and bedside healing that no machine can replicate!" },
          { text: "Nurses will stop talking to patients" },
        ],
        correctIndex: 2,
        explanation: "AI can monitor heart rates and flag drop in oxygen, but it can never hold a child's hand during an injection or comfort an anxious mother. Nursing remains one of the most AI-proof and compassionate professions on Earth.",
        proTip: "Healthcare will always be powered by human hearts and healing hands.",
      },
    ],
  },

  lawyer: {
    id: "lawyer",
    title: "Lawyer & Legal Roadmap Quiz",
    subtitle: "A student-friendly quiz for 8th, 9th & 10th classes: CLAT entrance, 5-year LL.B, courtroom debate, and fighting for justice!",
    icon: "⚖️",
    badge: "For Classes 8th – 10th",
    gradient: "from-amber-600 via-stone-700 to-stone-900",
    accentColor: "#78350F",
    description: "Love debating, logical arguments, and fighting for fairness and justice? Uncover the legal roadmap: choosing streams after 10th, cracking CLAT, studying in National Law Universities, and courtroom advocacy!",
    totalQuestions: 10,
    blueprintUrl: "/career-reports?career=lawyer",
    cheatSheet: [
      "Class 8-10: Participate in school debates, read books, improve English comprehension, and understand the Indian Constitution.",
      "After 10th: Any stream! (Arts/HEC, Commerce/CEC, or Science/MPC) — all streams can appear for law entrance exams.",
      "Two Main Degree Paths: 1) 5-Year Integrated BA-LLB / BBA-LLB directly after 12th; 2) 3-Year LLB after regular graduation.",
      "Premier Entrance Exam: CLAT (Common Law Admission Test) for India's 25+ National Law Universities (NLUs).",
      "License to Practice: Enrolling with a State Bar Council and clearing the All India Bar Examination (AIBE).",
      "Future with AI: AI will speed up contract drafting and legal research, but courtroom persuasion, judge cross-examination, and justice remain purely human!"
    ],
    questions: [
      {
        id: 1,
        roadmapStage: "Stage 1: Stream Selection after 10th",
        category: "Choosing Branch / Stream",
        categoryColor: "bg-blue-100 text-blue-900 border-blue-300",
        question: "Which stream should you pick in Intermediate (Class 11 & 12) if you want to become a Lawyer or Advocate in India?",
        options: [
          { text: "Only Science MPC is allowed" },
          { text: "Only Commerce is allowed" },
          { text: "Any stream you want! (Arts/HEC, Commerce/CEC, or Science/MPC) — all students are 100% eligible for law!" },
          { text: "You must take medical BiPC only" },
        ],
        correctIndex: 2,
        explanation: "Law has zero stream restrictions! Whether you studied Arts, Commerce, or Science in 10+2, you are eligible to appear for CLAT and enter top law universities.",
        proTip: "Arts and Humanities (History, Political Science, Economics) give you great contextual background for constitutional law!",
      },
      {
        id: 2,
        roadmapStage: "Stage 2: 5-Year Integrated Law Degree",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "What is the popular integrated 5-year undergraduate law course that students join directly after passing Class 12?",
        options: [
          { text: "B.Tech Computer Science" },
          { text: "B.A. LL.B (Hons) or B.B.A. LL.B (Hons) - 5 Years" },
          { text: "MBBS Medical Degree" },
          { text: "B.Sc Agriculture" },
        ],
        correctIndex: 1,
        explanation: "The 5-year integrated B.A. LL.B / B.B.A. LL.B program allows high school graduates to earn both a Bachelor of Arts/Business and a Bachelor of Law degree in a combined 5-year course.",
        proTip: "Integrated law saves you one full year compared to doing a 3-year graduation followed by a 3-year LLB!",
      },
      {
        id: 3,
        roadmapStage: "Stage 3: The Premier Law Entrance Exam",
        category: "College Degree & Exams",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "Which national entrance examination is written after Class 12 to enter India's top National Law Universities (NLUs)?",
        options: [
          { text: "CLAT (Common Law Admission Test)" },
          { text: "JEE Main Exam" },
          { text: "NEET Exam" },
          { text: "GATE Examination" },
        ],
        correctIndex: 0,
        explanation: "CLAT (Common Law Admission Test) is conducted annually for admission into 25+ prestigious National Law Universities (like NLSIU Bengaluru, NALSAR Hyderabad, and WBNUJS Kolkata).",
        proTip: "CLAT tests reading comprehension, current affairs, logical reasoning, and legal awareness — no complex math required!",
      },
      {
        id: 4,
        roadmapStage: "Stage 4: The 3-Year Route after Graduation",
        category: "Course Duration",
        categoryColor: "bg-emerald-100 text-emerald-900 border-emerald-300",
        question: "If you first complete a regular 3-year graduation (like B.A., B.Sc., or B.Com), how many years does a standard LL.B course take afterwards?",
        options: [
          { text: "1 Year" },
          { text: "10 Years" },
          { text: "6 Months" },
          { text: "3 Years (6 Semesters)" },
        ],
        correctIndex: 3,
        explanation: "Graduates in any field can write exams like DU LLB, State Law CET, or university law tests to enter a 3-year LL.B program to become full lawyers.",
        proTip: "Even engineers, doctors, and accountants often pursue 3-year LL.B to become corporate and patent lawyers!",
      },
      {
        id: 5,
        roadmapStage: "Stage 5: High School Foundation",
        category: "School Subjects",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "Which subjects in school right now in 8th, 9th, and 10th help you build the sharpest foundation for law?",
        options: [
          { text: "Algebraic equations only" },
          { text: "English (Reading Comprehension & Vocabulary) and Social Studies (Civics & Indian Constitution)" },
          { text: "Botany and Plant Anatomy" },
          { text: "Handicrafts and Wood Carving" },
        ],
        correctIndex: 1,
        explanation: "Lawyers work with words, texts, and arguments! Strong English reading speed, clear comprehension, and understanding the Fundamental Rights in Civics give you an enormous head start.",
        proTip: "Read diverse books, newspapers, and school debate topics to broaden your worldview.",
      },
      {
        id: 6,
        roadmapStage: "Stage 6: License to Practice (AIBE)",
        category: "College Degree & Exams",
        categoryColor: "bg-teal-100 text-teal-900 border-teal-300",
        question: "After graduating with an LL.B degree, what official exam must you pass to practice in courts across India?",
        options: [
          { text: "A physical fitness test" },
          { text: "A school board exam" },
          { text: "All India Bar Examination (AIBE) conducted by the Bar Council of India" },
          { text: "A typing speed test" },
        ],
        correctIndex: 2,
        explanation: "Law graduates enroll with their State Bar Council and must clear the All India Bar Examination (AIBE) within 2 years to receive their Certificate of Practice to argue cases before judges.",
        proTip: "Once you pass AIBE, you can wear the black coat and represent clients in courts of law!",
      },
      {
        id: 7,
        roadmapStage: "Stage 7: High School Skills to Practice",
        category: "Skills to Build",
        categoryColor: "bg-rose-100 text-rose-900 border-rose-300",
        question: "What activity in school gives you the best hands-on practice for becoming a skilled courtroom advocate?",
        options: [
          { text: "Sitting silently without ever speaking in class" },
          { text: "Copying homework from others without understanding" },
          { text: "Believing everything you read on social media without proof" },
          { text: "School debates, elocution competitions, model parliaments (MUN), and asking 'why' with logical evidence" },
        ],
        correctIndex: 3,
        explanation: "Debating teaches you how to structure an argument, listen to opposing views, stay calm under counter-questions, and persuade an audience using evidence and facts.",
        proTip: "Join your school debate team or literary club — it builds extraordinary self-confidence!",
      },
      {
        id: 8,
        roadmapStage: "Stage 8: Exciting Law Specialisations",
        category: "College Degree & Exams",
        categoryColor: "bg-indigo-100 text-indigo-900 border-indigo-300",
        question: "Law is not just about criminal courts! Which of the following are high-paying modern legal careers?",
        options: [
          { text: "Corporate Law (Companies & Mergers), Cyber Law, Intellectual Property (Copyrights/Patents), and Human Rights Law" },
          { text: "Only arguing parking ticket fines" },
          { text: "Selling law books at bus stations" },
          { text: "There are zero specialisations in law" },
        ],
        correctIndex: 0,
        explanation: "Modern law includes corporate lawyers advising Google and Apple, cyber lawyers protecting online privacy, environmental lawyers fighting pollution, and international human rights advocates.",
        proTip: "Corporate and Cyber lawyers are among the highest-paid professionals in modern business.",
      },
      {
        id: 9,
        roadmapStage: "Stage 9: What Lawyers Do Every Day",
        category: "Skills to Build",
        categoryColor: "bg-amber-100 text-amber-900 border-amber-300",
        question: "What does the day-to-day work of a dedicated lawyer involve?",
        options: [
          { text: "Only shouting dramatically like in movies" },
          { text: "Researching legal precedents, drafting agreements, advising clients, negotiating settlements, and presenting logical arguments in court" },
          { text: "Typing random letters in MS Paint" },
          { text: "Fixing courtroom air conditioners" },
        ],
        correctIndex: 1,
        explanation: "Real law is about thorough research, drafting clear contracts, understanding client problems, negotiating peaceful solutions, and presenting well-researched arguments before judges.",
        proTip: "90% of a lawyer's success comes from preparation and deep study before ever stepping into the courtroom!",
      },
      {
        id: 10,
        roadmapStage: "Stage 10: The Legal Profession in the AI Era",
        category: "AI & Future World",
        categoryColor: "bg-purple-100 text-purple-900 border-purple-300",
        question: "How will Artificial Intelligence (AI) transform law by the time you graduate from law school?",
        options: [
          { text: "Robots will replace all human judges and courts will be closed" },
          { text: "Laws will stop existing in all countries" },
          { text: "AI will summarize long case files and find legal precedents in seconds, while lawyers focus on strategic thinking, cross-examination, client counseling, and ethical justice!" },
          { text: "Lawyers will no longer need to study law" },
        ],
        correctIndex: 2,
        explanation: "AI will speed up legal research and review hundreds of contract pages in seconds. But justice, empathy, ethical judgment, moral principles, and persuasive courtroom advocacy will always remain uniquely human.",
        proTip: "A lawyer who masters legal reasoning and uses AI tools to research 10x faster will be an unstoppable champion of justice!",
      },
    ],
  },
};
