export interface CourseTopicItem {
  id: number;
  title: string;
  category: "Core Subject" | "Lab & Practical" | "Advanced / Project";
  description: string;
}

export interface CareerCurriculum {
  id: string;
  title: string;
  shortCode: string;
  icon: string;
  category: string;
  degreeTrack: string;
  duration: string;
  eligibilityAfterInter: string;
  oneLineSummary: string;
  topics: CourseTopicItem[];
}

export const ALL_18_CAREER_CURRICULA: CareerCurriculum[] = [
  {
    id: "swe",
    title: "Software Engineer",
    shortCode: "Software Engineer",
    icon: "💻",
    category: "Technology",
    degreeTrack: "B.Tech CSE / IT / BCA + MCA",
    duration: "4 Years (8 Semesters)",
    eligibilityAfterInter: "Intermediate with MPC + Entrance (JEE / State EAMCET)",
    oneLineSummary: "Learn coding languages, build web & mobile apps, manage databases, train AI models, and write software in computer labs.",
    topics: [
      { id: 1, title: "C & Python Programming", category: "Core Subject", description: "Writing code, logic building, loops, functions, and solving mathematical problems." },
      { id: 2, title: "Data Structures & Algorithms (DSA)", category: "Core Subject", description: "Trees, graphs, stacks, queues, and sorting algorithms for efficient software design." },
      { id: 3, title: "Programming Practicals & Coding Labs", category: "Lab & Practical", description: "Daily hands-on lab sessions writing and debugging programs in VS Code and Linux terminal." },
      { id: 4, title: "Object Oriented Programming (Java / C++)", category: "Core Subject", description: "Classes, inheritance, polymorphism, design patterns, and building desktop apps." },
      { id: 5, title: "Database Systems & SQL Lab", category: "Lab & Practical", description: "Designing database tables, writing SQL queries, and connecting PostgreSQL/MySQL to apps." },
      { id: 6, title: "Operating Systems & Linux Shell Scripting", category: "Core Subject", description: "Process scheduling, memory management, file systems, and bash terminal automation." },
      { id: 7, title: "Computer Networks & Sockets Lab", category: "Lab & Practical", description: "IP addressing, Wireshark packet analysis, routers, TCP/IP protocols, and client-server apps." },
      { id: 8, title: "Full Stack Web Development", category: "Core Subject", description: "Building modern websites using HTML5, CSS, JavaScript, React.js, and Node.js APIs." },
      { id: 9, title: "Software Engineering & Agile Git Practice", category: "Core Subject", description: "Team collaboration with GitHub, code version control, software testing, and Scrum sprints." },
      { id: 10, title: "Artificial Intelligence & Machine Learning Lab", category: "Lab & Practical", description: "Training predictive models in Python, Neural Networks, and image/text recognition." },
      { id: 11, title: "Cloud Computing & DevOps (AWS / Docker)", category: "Advanced / Project", description: "Deploying applications on AWS cloud servers, Docker containers, and CI/CD pipelines." },
      { id: 12, title: "Cybersecurity & Network Defense", category: "Core Subject", description: "Encryption, firewalls, ethical hacking basics, authentication, and secure coding." },
      { id: 13, title: "Major Capstone Software Project", category: "Advanced / Project", description: "Building an end-to-end working software product or mobile app from scratch with team." },
      { id: 14, title: "Industry Internship (6 Months)", category: "Advanced / Project", description: "Working directly inside an IT company on real client projects before graduation." },
    ],
  },
  {
    id: "engineer",
    title: "Engineer (Core / Mechanical / Civil / EEE / ECE)",
    shortCode: "Engineer",
    icon: "⚙️",
    category: "Engineering & Tech",
    degreeTrack: "B.Tech / B.E. (Mechanical / Civil / EEE / ECE / Chemical / Robotics)",
    duration: "4 Years (8 Semesters)",
    eligibilityAfterInter: "Intermediate with MPC (Maths, Physics, Chemistry) + Entrance (JEE / State EAPCET)",
    oneLineSummary: "Study core science, CAD drafting, workshop manufacturing, circuits, thermodynamics, materials testing, and build physical machines or infrastructure.",
    topics: [
      { id: 1, title: "Engineering Mathematics & Calculus", category: "Core Subject", description: "Differential equations, linear algebra, Laplace transforms, and numerical methods for technical modeling." },
      { id: 2, title: "Engineering Physics & Materials Science Lab", category: "Lab & Practical", description: "Wave optics, semiconductors, crystal structures, magnetic materials, and laser physics experiments." },
      { id: 3, title: "Computer-Aided Design (CAD) & Drafting Lab", category: "Lab & Practical", description: "2D drafting and 3D modeling using AutoCAD, SolidWorks, and CATIA for machine parts and blueprints." },
      { id: 4, title: "Workshop Practice & Manufacturing Lab", category: "Lab & Practical", description: "Hands-on metal fitting, electric welding, carpentry, smithy, sheet metal, and modern CNC lathe operations." },
      { id: 5, title: "Basic Electrical & Electronics Engineering Lab", category: "Lab & Practical", description: "Circuit laws (Ohm's/Kirchhoff's), AC/DC power, diodes, transistors, transformers, and multimeter measurements." },
      { id: 6, title: "Engineering Mechanics & Statics", category: "Core Subject", description: "Forces, moments, equilibrium, friction, truss analysis, and center of gravity in mechanical and civil structures." },
      { id: 7, title: "Programming & Problem Solving in Python / C Lab", category: "Lab & Practical", description: "Writing foundational code for engineering computations, numerical plotting, and algorithmic problem solving." },
      { id: 8, title: "Strength of Materials & UTM Testing Lab", category: "Lab & Practical", description: "Testing tensile, compressive, and shear strength of steel, concrete, and composite alloys on UTM machines." },
      { id: 9, title: "Thermodynamics & Heat Transfer", category: "Core Subject", description: "Laws of thermodynamics, steam tables, refrigeration cycles, heat exchangers, combustion, and energy conversion." },
      { id: 10, title: "Fluid Mechanics & Hydraulic Machinery Lab", category: "Lab & Practical", description: "Fluid pressure, Bernoulli's principle, pipe friction, flow meters, Pelton turbines, and centrifugal pumps." },
      { id: 11, title: "Sensors, Control Systems & PLC Automation", category: "Core Subject", description: "Industrial sensors, feedback control loops, microcontrollers, PLCs, and SCADA automation basics." },
      { id: 12, title: "Environmental Engineering & Industrial Safety", category: "Core Subject", description: "Industrial pollution control, wastewater management, factory safety regulations, and ISO standards." },
      { id: 13, title: "Major Capstone Engineering Design Project", category: "Advanced / Project", description: "Multidisciplinary team design, calculation, 3D simulation, physical prototype fabrication, and testing." },
      { id: 14, title: "6-Month Industrial Plant / Site Internship", category: "Advanced / Project", description: "Practical on-site training in manufacturing plants, construction sites, power grids, or core industrial setups." },
    ],
  },
  {
    id: "doctor",
    title: "Doctor (MBBS)",
    shortCode: "Doctor",
    icon: "🩺",
    category: "Medical",
    degreeTrack: "MBBS (Bachelor of Medicine & Bachelor of Surgery)",
    duration: "5.5 Years (4.5 Years College + 1 Year Hospital Internship)",
    eligibilityAfterInter: "Intermediate with BiPC + NEET-UG Qualified",
    oneLineSummary: "Study human body anatomy, diagnose illnesses, prescribe medicines, assist in surgeries, and treat patients in hospital wards.",
    topics: [
      { id: 1, title: "Human Anatomy & Cadaver Dissection Lab", category: "Lab & Practical", description: "Dissecting human bodies to learn organs, muscles, blood vessels, and nervous system." },
      { id: 2, title: "Human Physiology & Blood Lab", category: "Lab & Practical", description: "Testing blood groups, hemoglobin, lung volume spirometry, and recording 12-lead ECGs." },
      { id: 3, title: "Medical Biochemistry", category: "Core Subject", description: "Blood glucose, kidney/liver function tests, vitamins, enzymes, and bodily metabolism." },
      { id: 4, title: "Pathology & Disease Biopsy Lab", category: "Lab & Practical", description: "Examining diseased tissues, tumors, and blood cells under high-power microscopes." },
      { id: 5, title: "Medical Microbiology & Bacterial Culture", category: "Lab & Practical", description: "Growing bacteria, identifying viruses, and testing antibiotic sensitivity discs." },
      { id: 6, title: "Pharmacology & Medicine Prescription", category: "Core Subject", description: "How medicines work, dosages, drug interactions, side effects, and writing prescriptions." },
      { id: 7, title: "Forensic Medicine & Autopsy Postings", category: "Lab & Practical", description: "Post-mortem examination, determining causes of death, injury patterns, and poisons." },
      { id: 8, title: "Community Medicine & Village Health Camps", category: "Lab & Practical", description: "Visiting villages, vaccination drives, public hygiene, and epidemic control." },
      { id: 9, title: "Eye (Ophthalmology) & ENT Clinics", category: "Core Subject", description: "Testing vision, examining retina, treating cataracts, ear infections, and sinus issues." },
      { id: 10, title: "General Medicine & Daily Ward Rounds", category: "Lab & Practical", description: "Taking patient histories, diagnosing fever, diabetes, heart diseases, and stroke." },
      { id: 11, title: "General Surgery & Operation Theatre (OT)", category: "Lab & Practical", description: "Sterile scrubbing, stitching wounds, assisting in appendectomy and trauma surgeries." },
      { id: 12, title: "Obstetrics & Gynaecology (Labor Room)", category: "Lab & Practical", description: "Pregnancy care, conducting normal deliveries, and treating women's health conditions." },
      { id: 13, title: "Paediatrics (Child Healthcare)", category: "Core Subject", description: "Treating newborn babies, monitoring child growth milestones, and pediatric infections." },
      { id: 14, title: "1-Year Compulsory Paid Hospital Internship", category: "Advanced / Project", description: "24x7 rotatory hospital training in Emergency, ICU, OPD, Surgery, and Rural Health Centres." },
    ],
  },
  {
    id: "police",
    title: "Police Officer (SI / DSP)",
    shortCode: "Police",
    icon: "👮",
    category: "Uniformed Services",
    degreeTrack: "Any Graduation Degree + State Police Academy Training",
    duration: "3-4 Years Degree + 1 Year Police Academy Training",
    eligibilityAfterInter: "Any Degree (BA / B.Sc / B.Com / B.Tech) + Police Recruitment Exam (SI / Constable / Group-1)",
    oneLineSummary: "Study criminal law, IPC sections, crime scene investigation, firearms handling, physical fitness, and police station management.",
    topics: [
      { id: 1, title: "Indian Penal Code (IPC / BNS) & Criminal Law", category: "Core Subject", description: "Studying criminal offences, murder, theft, fraud, cyber crimes, and lawful punishments." },
      { id: 2, title: "Code of Criminal Procedure (CrPC) & Arrest Rules", category: "Core Subject", description: "Rules for making arrests, search warrants, FIR registration, remand, and bail procedures." },
      { id: 3, title: "Indian Evidence Act & Court Proof", category: "Core Subject", description: "Valid crime evidence, eyewitness statements, digital evidence, and court testimony." },
      { id: 4, title: "Crime Scene Investigation & Forensics Lab", category: "Lab & Practical", description: "Fingerprint lifting, blood splatter analysis, footprint tracing, and weapon evidence collection." },
      { id: 5, title: "FIR Drafting & Case Diary Maintenance", category: "Lab & Practical", description: "Drafting First Information Reports (FIR), charge sheets, and investigation diaries." },
      { id: 6, title: "Cyber Crime & Mobile Forensics Training", category: "Lab & Practical", description: "Tracking fraud IP addresses, Call Detail Records (CDR), bank frauds, and cyber tracing." },
      { id: 7, title: "Firearms Handling & Target Shooting Practice", category: "Lab & Practical", description: "Shooting range training with Glock pistols, AK-47, Insas rifles, cleaning, and safety." },
      { id: 8, title: "Unarmed Combat (UAC) & Self-Defense", category: "Lab & Practical", description: "Karate, judo holds, disarming armed attackers, and crowd restraint techniques." },
      { id: 9, title: "Physical Endurance & Drill Training", category: "Lab & Practical", description: "Daily 5km running, obstacle courses, parade drills, route marches, and obstacle clearing." },
      { id: 10, title: "Crowd Control & Riot Management (Lathi Charge / Tear Gas)", category: "Lab & Practical", description: "Managing mob violence, tear gas deployment, barricading, and VIP security escorts." },
      { id: 11, title: "Traffic Management & Breathalyzer Law", category: "Core Subject", description: "Motor Vehicles Act, highway patrolling, speed radars, and drunk driving checkpoints." },
      { id: 12, title: "Human Rights & Community Policing", category: "Core Subject", description: "Protecting women/child rights, preventing custodial abuse, and friendly citizen policing." },
      { id: 13, title: "Police Station Station-In-Charge Attachment", category: "Advanced / Project", description: "3-month practical attachment managing daily complaints inside a local police station." },
      { id: 14, title: "Court Trial Observation & Conviction Practice", category: "Advanced / Project", description: "Attending Sessions Court, giving witness evidence, and executing arrest warrants." },
    ],
  },
  {
    id: "ias",
    title: "IAS (Indian Administrative Service)",
    shortCode: "IAS",
    icon: "🏛️",
    category: "Civil Services",
    degreeTrack: "Any Graduation Degree + UPSC Civil Services Exam + LBSNAA Training",
    duration: "3-4 Years Degree + 2 Years Academy & District Training",
    eligibilityAfterInter: "Any Degree (BA / B.Sc / B.Com / B.Tech) + UPSC CSE Exam (Age 21+)",
    oneLineSummary: "Study Indian constitution, governance, economy, policy making, public administration, and district collectorate administration.",
    topics: [
      { id: 1, title: "Indian Constitution & Governance (Polity)", category: "Core Subject", description: "Parliament, Prime Minister powers, fundamental rights, judiciary, and state federalism." },
      { id: 2, title: "Indian Economy & Budgeting", category: "Core Subject", description: "GDP growth, taxation, banking, agriculture subsidies, poverty alleviation, and RBI policies." },
      { id: 3, title: "History & Indian Heritage / Culture", category: "Core Subject", description: "Ancient, medieval, modern freedom struggle, social reforms, and art architectures." },
      { id: 4, title: "Geography & Disaster Management", category: "Core Subject", description: "Monsoons, rivers, soil resources, earthquakes, cyclone response, and climate change policies." },
      { id: 5, title: "Ethics, Integrity & Public Aptitude", category: "Core Subject", description: "Moral decision making, anti-corruption rules, empathy for poor, and civil service ethics." },
      { id: 6, title: "International Relations & Foreign Policy", category: "Core Subject", description: "India-US, India-China relations, UN treaties, global trade, and international diplomacy." },
      { id: 7, title: "Optional Subject Specialization (e.g., PSIR / Sociology / Public Admin)", category: "Core Subject", description: "Deep academic master-level mastery of chosen UPSC optional subject papers." },
      { id: 8, title: "Answer Writing & Essay Drafting Practice", category: "Lab & Practical", description: "Daily timed drafting of 250-word policy answers and structured socio-economic essays." },
      { id: 9, title: "LBSNAA Foundation Course & Himalayan Trek", category: "Lab & Practical", description: "Joint civil services training in Mussoorie with fitness drills, horse riding, and village visits." },
      { id: 10, title: "Land Revenue & District Administration Law", category: "Core Subject", description: "Land records (Pahani), land acquisition for projects, revenue courts, and survey systems." },
      { id: 11, title: "Law & Order Management as Sub-Divisional Magistrate (SDM)", category: "Lab & Practical", description: "Imposing Section 144, handling election duties, disaster relief, and communal peace." },
      { id: 12, title: "Welfare Scheme Implementation & Public Audits", category: "Lab & Practical", description: "Inspecting MGNREGA works, public distribution ration shops, and government hospitals." },
      { id: 13, title: "1-Year District Practical Training Attachment", category: "Advanced / Project", description: "Working hands-on under a District Collector handling tehsils, zilla parishad, and courts." },
      { id: 14, title: "Central Secretariat Attachment in New Delhi", category: "Advanced / Project", description: "Formulating national policy files and ministry budget allocations in Central Government." },
    ],
  },
  {
    id: "ips",
    title: "IPS (Indian Police Service)",
    shortCode: "IPS",
    icon: "🛡️",
    category: "Civil Services",
    degreeTrack: "Any Graduation Degree + UPSC CSE + SVPNPA National Police Academy",
    duration: "3-4 Years Degree + 2 Years Elite Academy & District Training",
    eligibilityAfterInter: "Any Degree + UPSC CSE Exam + Physical Fitness Standards",
    oneLineSummary: "Master criminal investigation, anti-terror operations, forensic science, riot control, and lead district police forces as SP.",
    topics: [
      { id: 1, title: "UPSC General Studies (Polity, Economy, History)", category: "Core Subject", description: "Constitutional law, national security, governance, and socio-economic policies." },
      { id: 2, title: "Criminal Minor & Major Acts (IPC, CrPC, Evidence Act)", category: "Core Subject", description: "Deep legal mastery of criminal offences, investigative powers, and courtroom evidence." },
      { id: 3, title: "Advanced Forensic Science & Ballistics Lab", category: "Lab & Practical", description: "Gunshot residue analysis, DNA profiling, narco analysis rules, and handwriting examination." },
      { id: 4, title: "Cyber Warfare & Darknet Intelligence", category: "Lab & Practical", description: "Tracking crypto extortion, darknet drug cartels, ransomware, and telecommunication intercepts." },
      { id: 5, title: "Tactical Weapons & Assault Rifle Firing", category: "Lab & Practical", description: "Combat tactical firing with Glock 9mm, MP5 submachine guns, AK-47, and sniper rifles." },
      { id: 6, title: "Physical Fitness, Horse Riding & Obstacle Assault", category: "Lab & Practical", description: "Cross-country marathon runs, equestrian horse riding, swimming, and battle obstacle courses." },
      { id: 7, title: "VIP Security & Anti-Sabotage Drills", category: "Lab & Practical", description: "Z+ security convoy protocols, motorcade planning, bomb detection, and bulletproof screening." },
      { id: 8, title: "Internal Security & Anti-Naxal / Counter-Terror Operations", category: "Lab & Practical", description: "Jungle warfare survival, ambush counter-tactics, cordon-and-search, and intelligence networks." },
      { id: 9, title: "Crowd Control, Riot Management & Tear Smoke", category: "Lab & Practical", description: "Managing communal riots, non-lethal weapon deployment, and rapid action force commanding." },
      { id: 10, title: "Police Leadership & Police Station Administration", category: "Core Subject", description: "Managing police manpower, station lockups, citizen grievance portals, and crime tracking." },
      { id: 11, title: "Army & Paramilitary Attachment (Greyhounds / CRPF / NSG)", category: "Lab & Practical", description: "Training with elite commando units in counter-insurgency and urban hostage rescue." },
      { id: 12, title: "Human Rights, Juvenile Justice & Police Ethics", category: "Core Subject", description: "Ensuring zero custodial violence, transparent investigation, and juvenile reform rules." },
      { id: 13, title: "District Practical Training as ASP (1 Year)", category: "Advanced / Project", description: "Independent charge as Assistant Superintendent of Police commanding sub-division police." },
      { id: 14, title: "Leading High-Profile Crime Investigations", category: "Advanced / Project", description: "Solving real murder, kidnapping, and organized crime syndicates before full SP posting." },
    ],
  },
  {
    id: "army",
    title: "Indian Army (Officer / Soldier)",
    shortCode: "Indian Army",
    icon: "🎖️",
    category: "Defence",
    degreeTrack: "National Defence Academy (NDA) / Indian Military Academy (IMA) / Agniveer",
    duration: "3-4 Years Military Academy Training",
    eligibilityAfterInter: "10+2 with MPC (for NDA Army/AirForce/Navy) or Any Degree (for CDS / OTA)",
    oneLineSummary: "Undergo tactical battle training, weapons firing, navigation, military strategy, physical fitness, and lead troops on border defence.",
    topics: [
      { id: 1, title: "Military History & Strategic Warfare", category: "Core Subject", description: "Study of famous global battles, Kargil war tactics, geopolitics, and battlefield strategy." },
      { id: 2, title: "Physical Conditioning & Battle Obstacle Course (BPET)", category: "Lab & Practical", description: "5km endurance battle runs with 20kg backpack, rope climbing, and 9-foot ditch clearing." },
      { id: 3, title: "Weapons Firing & Marksmanship Range", category: "Lab & Practical", description: "Stripping, assembling, and precision shooting with INSAS rifles, LMG, rocket launchers, and pistols." },
      { id: 4, title: "Map Reading & Tactical Night Navigation", category: "Lab & Practical", description: "Navigating deep jungles and mountains using prismatic compass, GPS, contour maps, and stars." },
      { id: 5, title: "Field Craft & Battle Tactics (FC & BC)", category: "Lab & Practical", description: "Camouflage concealment, crawling techniques, trench digging, and section attack formations." },
      { id: 6, title: "Unarmed Combat (Ghatak Commando Martial Arts)", category: "Lab & Practical", description: "Hand-to-hand combat, knife defense, sentry silencing, and survival martial arts." },
      { id: 7, title: "Military Leadership & Officer Character", category: "Core Subject", description: "Commanding troops under extreme danger, quick battle decision making, and army ethics." },
      { id: 8, title: "Military Law & Army Act, 1950", category: "Core Subject", description: "Court martial procedures, rules of engagement, Geneva conventions, and military discipline." },
      { id: 9, title: "Radio Communication & Electronic Signal Warfare", category: "Lab & Practical", description: "Operating encrypted army VHF/UHF wireless sets, cryptographic radio codes, and jamming." },
      { id: 10, title: "Counter-Terrorism & Jungle Warfare Drills", category: "Lab & Practical", description: "Room intervention, clearing terrorist hideouts, hostage extraction, and cordon operations." },
      { id: 11, title: "Combat Engineering & Explosives Handling", category: "Lab & Practical", description: "Laying and clearing minefields, constructing temporary bridges, and detonating explosives." },
      { id: 12, title: "High Altitude & Cold Weather Warfare Survival", category: "Lab & Practical", description: "Surviving at -30°C in glaciers, snow tent pitching, frostbite prevention, and skiing." },
      { id: 13, title: "Final Term Passing Out Parade & Commissioning", category: "Advanced / Project", description: "Marching on the sacred Chetwode drill square and earning the prestigious Lieutenant stars." },
      { id: 14, title: "Frontline Border Post Deployment (6 Months)", category: "Advanced / Project", description: "Commanding a 30-soldier infantry platoon on actual LoC / international border duty." },
    ],
  },
  {
    id: "ca",
    title: "Chartered Accountant (CA)",
    shortCode: "CA (ICAI)",
    icon: "📊",
    category: "Finance",
    degreeTrack: "ICAI Professional Course (Foundation + Inter + Final + Articleship)",
    duration: "3.5 to 4.5 Years",
    eligibilityAfterInter: "10+2 (Any stream, Commerce preferred) or Any Graduate",
    oneLineSummary: "Master financial accounting, company balance sheets, corporate audits, Income Tax/GST filing, and 2-year firm articleship.",
    topics: [
      { id: 1, title: "Financial Accounting & Bookkeeping", category: "Core Subject", description: "Journal entries, ledgers, trial balance, depreciation, and final company balance sheets." },
      { id: 2, title: "Business & Corporate Laws (Companies Act)", category: "Core Subject", description: "Indian Contract Act, Partnership Act, LLP rules, and company governance laws." },
      { id: 3, title: "Business Mathematics & Financial Calculations", category: "Core Subject", description: "Compound interest, annuities, ratios, statistical dispersion, and probability." },
      { id: 4, title: "Business Economics & Macro Market Analysis", category: "Core Subject", description: "Supply-demand elasticity, market competition structures, inflation, and national GDP." },
      { id: 5, title: "Advanced Accounting & Indian Accounting Standards (Ind AS)", category: "Core Subject", description: "Company amalgamations, group holding accounts, and corporate financial reporting." },
      { id: 6, title: "Income Tax Law & Return Filing", category: "Core Subject", description: "Calculating tax on salary, house property, business profits, capital gains, and filing ITR." },
      { id: 7, title: "Goods & Services Tax (GST) & Input Tax Credit", category: "Core Subject", description: "CGST/SGST rules, GST invoice generation, input credit calculation, and monthly filing." },
      { id: 8, title: "Cost & Management Accounting", category: "Core Subject", description: "Product pricing, manufacturing cost breakdown, break-even analysis, and standard costing." },
      { id: 9, title: "Auditing Standards & Fraud Detection", category: "Core Subject", description: "Checking company books, verifying invoices, internal controls, and issuing audit reports." },
      { id: 10, title: "ICITSS Computer Lab & Tally ERP Training", category: "Lab & Practical", description: "4-week mandatory hands-on practical lab in Advanced Excel, TallyPrime, and e-filing portals." },
      { id: 11, title: "Strategic Financial Management (SFM)", category: "Core Subject", description: "Stock market investments, portfolio management, foreign exchange, and mergers/acquisitions." },
      { id: 12, title: "Corporate & International Taxation", category: "Core Subject", description: "Corporate tax planning, MAT, transfer pricing, and cross-border double taxation treaties." },
      { id: 13, title: "2-Year Mandatory Practical Articleship", category: "Advanced / Project", description: "Full-time work inside a practicing CA firm auditing real companies, banks, and businesses." },
      { id: 14, title: "Forensic Accounting & Business Valuation", category: "Advanced / Project", description: "Investigating financial scams, evaluating startup company net worth, and advisory." },
    ],
  },
  {
    id: "lawyer",
    title: "Lawyer / Advocate",
    shortCode: "Lawyer",
    icon: "⚖️",
    category: "Law",
    degreeTrack: "5-Year Integrated B.A. LL.B / BBA LL.B or 3-Year LL.B after Degree",
    duration: "5 Years (Integrated) or 3 Years (after Degree)",
    eligibilityAfterInter: "10+2 (Any stream) + Entrance (CLAT / State LAWCET)",
    oneLineSummary: "Study criminal laws, constitutional rights, civil property disputes, contract drafting, and practice advocacy in moot courts.",
    topics: [
      { id: 1, title: "Legal Methods & Court System Structure", category: "Core Subject", description: "Hierarchy of Indian courts, reading Supreme Court judgments, and legal terminology." },
      { id: 2, title: "Law of Torts & Consumer Protection", category: "Core Subject", description: "Accident negligence claims, defamation, consumer court disputes, and liability." },
      { id: 3, title: "Constitutional Law & Fundamental Rights", category: "Core Subject", description: "Articles 14 (Equality), 19 (Freedom of Speech), 21 (Right to Life), and filing High Court Writs." },
      { id: 4, title: "Law of Contracts & Commercial Agreements", category: "Core Subject", description: "Valid contract rules, breach of contract penalties, loan guarantees, and commercial terms." },
      { id: 5, title: "Contract Drafting & Negotiation Workshop", category: "Lab & Practical", description: "Drafting real employment agreements, rental deeds, and non-disclosure agreements (NDAs)." },
      { id: 6, title: "Family Law (Marriage, Divorce & Inheritance)", category: "Core Subject", description: "Marriage laws, alimony maintenance, child custody, and ancestral property division." },
      { id: 7, title: "Criminal Law & Offences (IPC / BNS)", category: "Core Subject", description: "Theft, murder, fraud, cyber crimes, self-defense rules, and criminal punishments." },
      { id: 8, title: "Criminal Procedure & Police Investigation (CrPC)", category: "Core Subject", description: "Filing FIR, police arrest rules, bail applications, remands, and criminal trials." },
      { id: 9, title: "Law of Evidence & Witness Examination", category: "Core Subject", description: "Valid court evidence, dying declarations, digital proof, and cross-examining witnesses." },
      { id: 10, title: "Civil Procedure Code & Property Suits (CPC)", category: "Core Subject", description: "Filing civil suits, land dispute injunctions, recovery petitions, and court execution." },
      { id: 11, title: "Company Law & Corporate Governance", category: "Core Subject", description: "Starting a private company, director responsibilities, shareholder rights, and mergers." },
      { id: 12, title: "Moot Court Competitions & Trial Advocacy Lab", category: "Lab & Practical", description: "Practicing simulated trials, arguing cases before judges, and presenting legal memorials." },
      { id: 13, title: "Drafting, Pleading & Conveyancing Clinic", category: "Lab & Practical", description: "Writing civil plaints, bail petitions, affidavits, wills, and power of attorney documents." },
      { id: 14, title: "Legal Aid Clinic & Court Internship (20 Weeks)", category: "Advanced / Project", description: "Attending live District/High Court trials and providing free legal advice to needy citizens." },
    ],
  },
  {
    id: "nurse",
    title: "Nurse",
    shortCode: "Nurse",
    icon: "💉",
    category: "Medical & Healthcare",
    degreeTrack: "B.Sc Nursing (Bachelor of Science in Nursing) / GNM",
    duration: "4 Years (B.Sc) / 3 Years (GNM)",
    eligibilityAfterInter: "Intermediate with BiPC (Biology, Physics, Chemistry)",
    oneLineSummary: "Learn patient bedside care, IV injections, wound dressings, emergency CPR, ICU monitoring, and assist in childbirth in hospitals.",
    topics: [
      { id: 1, title: "Applied Human Anatomy & Physiology", category: "Core Subject", description: "Study of human organs, heart, lungs, bones, muscles, and circulatory pathways." },
      { id: 2, title: "Nursing Foundations & Clinical Skills Lab", category: "Lab & Practical", description: "Checking temperature/BP, bed making, patient hygiene, feeding tubes, and catheterization." },
      { id: 3, title: "Injections, IV Cannula & Medication Administration", category: "Lab & Practical", description: "Administering IV drips, intramuscular/subcutaneous injections, and calculating dosages." },
      { id: 4, title: "Medical-Surgical Hospital Ward Postings", category: "Lab & Practical", description: "Caring for admitted hospital patients with fever, heart issues, diabetes, and fractures." },
      { id: 5, title: "Wound Dressing & Surgical Care", category: "Lab & Practical", description: "Sterile dressing of postoperative surgical wounds, burns, and stitch removals." },
      { id: 6, title: "Microbiology, Infection Control & Hospital Hygiene", category: "Core Subject", description: "Sterilizing instruments, autoclave operations, preventing hospital infections, and PPE." },
      { id: 7, title: "Pharmacology for Nurses", category: "Core Subject", description: "Antibiotics, emergency injections (Adrenaline, Atropine), IV fluids, and side effects." },
      { id: 8, title: "Operation Theatre (OT) & Scrub Nurse Training", category: "Lab & Practical", description: "Setting up sterile surgical trays, assisting surgeons, and handling anesthesia equipment." },
      { id: 9, title: "Emergency Trauma & ICU Monitoring (CPR)", category: "Lab & Practical", description: "Operating cardiac monitors, oxygen masks, ventilators, suction, and emergency CPR." },
      { id: 10, title: "Obstetrics & Midwifery (Labor Room Postings)", category: "Lab & Practical", description: "Antenatal mother checks, monitoring contractions, and assisting newborn deliveries." },
      { id: 11, title: "Child Health & Newborn Care (Paediatrics)", category: "Lab & Practical", description: "Caring for premature infants in baby warmers, phototherapy, and child vaccinations." },
      { id: 12, title: "Mental Health & Psychiatric Nursing", category: "Core Subject", description: "Counselling patients with depression, anxiety, dementia, and psychiatric rehabilitation." },
      { id: 13, title: "Community Health Nursing in Rural Villages", category: "Lab & Practical", description: "Visiting village households, school health checkups, and mother-child nutrition camps." },
      { id: 14, title: "Final Year Full-Time Hospital Clinical Internship", category: "Advanced / Project", description: "Independent night shifts and day shifts managing hospital inpatient wards before degree." },
    ],
  },
  {
    id: "pharmacist",
    title: "Pharmacist",
    shortCode: "Pharmacist",
    icon: "💊",
    category: "Medical & Healthcare",
    degreeTrack: "B.Pharmacy (Bachelor of Pharmacy) / Pharm.D",
    duration: "4 Years (B.Pharm) / 6 Years (Pharm.D)",
    eligibilityAfterInter: "Intermediate with BiPC or MPC + State Pharmacy Entrance",
    oneLineSummary: "Learn how to manufacture tablets, syrups, analyze chemical purity, test drug effects on organs, and manage hospital pharmacies.",
    topics: [
      { id: 1, title: "Pharmaceutics & Medicine Formulation Lab", category: "Lab & Practical", description: "Making syrups, ointments, suspensions, and formulating tablets from raw powders." },
      { id: 2, title: "Pharmaceutical Chemistry Lab", category: "Lab & Practical", description: "Synthesizing medicine compounds like Aspirin and testing purity of chemical ingredients." },
      { id: 3, title: "Human Anatomy & Physiology for Pharmacy", category: "Core Subject", description: "How the human cardiovascular, digestive, nervous, and renal systems function." },
      { id: 4, title: "Pharmacognosy & Herbal Medicine Lab", category: "Lab & Practical", description: "Extracting active medicinal chemicals from medicinal plants, leaves, and roots." },
      { id: 5, title: "Pharmaceutical Analysis & Spectrophotometry Lab", category: "Lab & Practical", description: "Using UV spectrometers and chromatography to test accurate drug percentage in pills." },
      { id: 6, title: "Pharmacology & Drug Action on Organs Lab", category: "Lab & Practical", description: "Studying how blood pressure, heart, and pain medications act on body tissues." },
      { id: 7, title: "Pharmaceutical Microbiology Lab", category: "Lab & Practical", description: "Sterilizing injection vials, testing antibiotics, and operating cleanrooms." },
      { id: 8, title: "Medicinal Chemistry & Drug Design", category: "Core Subject", description: "Chemical structures of antibiotics, antiviral, anticancer, and painkiller drugs." },
      { id: 9, title: "Industrial Tablet Machine & Capsule Lab", category: "Lab & Practical", description: "Operating rotary tablet punch machines, capsule filling, and hardness testing." },
      { id: 10, title: "Biopharmaceutics & Drug Absorption", category: "Core Subject", description: "How drugs get absorbed in stomach, distributed in blood, and excreted by kidneys." },
      { id: 11, title: "Hospital & Community Pharmacy Practice", category: "Core Subject", description: "Dispensing medicines, reading doctors' prescriptions, and patient dosage counselling." },
      { id: 12, title: "Pharmacy Law & Drug Regulatory Affairs (FDA)", category: "Core Subject", description: "Drugs & Cosmetics Act, medical store licensing, clinical trial approvals, and patents." },
      { id: 13, title: "Pharmaceutical Factory In-Plant Training (1 Month)", category: "Advanced / Project", description: "Hands-on training inside a GMP certified medicine manufacturing plant." },
      { id: 14, title: "Hospital Pharmacy Clinical Internship", category: "Advanced / Project", description: "Managing inpatient hospital pharmacy stock, IV preparations, and drug safety." },
    ],
  },
  {
    id: "agri",
    title: "Agricultural Officer",
    shortCode: "Agri Officer",
    icon: "🌾",
    category: "Agriculture",
    degreeTrack: "B.Sc. (Hons) Agriculture",
    duration: "4 Years (8 Semesters)",
    eligibilityAfterInter: "Intermediate with BiPC or MPC + State Agri Entrance (EAMCET / ICAR)",
    oneLineSummary: "Study crop cultivation, soil health, pest control, plant genetics, organic farming, and spend 6 months working in rural villages.",
    topics: [
      { id: 1, title: "Agronomy & Crop Production Principles", category: "Core Subject", description: "Seed sowing techniques, crop seasons (Kharif/Rabi), spacing, and farming practices." },
      { id: 2, title: "Soil Science & Soil Testing Lab", category: "Lab & Practical", description: "Testing soil pH, nitrogen, phosphorus, potassium nutrients, and fertilizer dosage." },
      { id: 3, title: "Agricultural Meteorology & Climate", category: "Core Subject", description: "Rainfall patterns, temperature, weather forecasting, and drought management for crops." },
      { id: 4, title: "Field Crop Cultivation Plots (Paddy, Cotton, Maize)", category: "Lab & Practical", description: "Hands-on growing of crops in college farm plots from seed sowing to harvesting." },
      { id: 5, title: "Plant Genetics & Seed Breeding Lab", category: "Lab & Practical", description: "Hybrid seed creation, flower emasculation, and breeding high-yielding crop varieties." },
      { id: 6, title: "Entomology & Insect Pest Control Lab", category: "Lab & Practical", description: "Identifying crop-destroying insects, caterpillars, and preparing biocontrol solutions." },
      { id: 7, title: "Plant Pathology & Disease Diagnosis Lab", category: "Lab & Practical", description: "Identifying leaf spot, rust, bacterial blight, and spraying proper fungicides." },
      { id: 8, title: "Horticulture (Fruits, Vegetables & Flowers)", category: "Core Subject", description: "Mango/citrus orchards, polyhouse vegetable farming, grafting, and landscaping." },
      { id: 9, title: "Agricultural Engineering & Drip Irrigation Lab", category: "Lab & Practical", description: "Tractor operation, drip/sprinkler pipe setups, water pumps, and solar farm tools." },
      { id: 10, title: "Organic Farming & Bio-Fertilizers Lab", category: "Lab & Practical", description: "Making vermicompost, Jeevamrutham, bio-pesticides, and natural soil enrichers." },
      { id: 11, title: "Post-Harvest Technology & Food Storage", category: "Core Subject", description: "Grain drying, cold storage, fruit preservation, food processing, and packaging." },
      { id: 12, title: "Agri-Business & Crop Marketing Economics", category: "Core Subject", description: "Mandi prices, crop insurance, MSP rates, farmer loan schemes, and export business." },
      { id: 13, title: "RAWE: 6-Month Rural Village Attachment", category: "Advanced / Project", description: "Living with farming families in a village, solving farm problems, and giving guidance." },
      { id: 14, title: "Agro-Industrial Hands-on Internship", category: "Advanced / Project", description: "Internship at seed processing plants, fertilizer factories, or commercial nurseries." },
    ],
  },
  {
    id: "bank",
    title: "Bank PO / Banking Officer",
    shortCode: "Bank PO",
    icon: "🏦",
    category: "Finance & Banking",
    degreeTrack: "Any Graduation Degree (B.Com / B.Sc / B.Tech / BA) + IBPS / SBI PO Exam",
    duration: "3-4 Years Degree + Bank Probation Training",
    eligibilityAfterInter: "Any Graduation Degree (Age 20-30)",
    oneLineSummary: "Study retail banking operations, home/crop loans, credit risk analysis, fraud prevention, investments, and foreign exchange.",
    topics: [
      { id: 1, title: "Quantitative Aptitude & Speed Mathematics", category: "Core Subject", description: "Data interpretation (DI), percentages, ratios, time & work, interest, and quick calculations." },
      { id: 2, title: "Logical Reasoning & Analytical Puzzles", category: "Core Subject", description: "Seating arrangements, syllogisms, blood relations, input-output, and critical thinking." },
      { id: 3, title: "English Comprehension & Official Bank Drafting", category: "Core Subject", description: "Reading comprehension, business vocabulary, error spotting, and formal banking emails." },
      { id: 4, title: "Principles & Practices of Banking (RBI Regulations)", category: "Core Subject", description: "Repo rates, CRR/SLR reserve ratios, KYC guidelines, and types of bank accounts." },
      { id: 5, title: "Retail Loans (Home, Vehicle, Education, Gold Loans)", category: "Core Subject", description: "Verifying borrower salary, property valuation, CIBIL credit score check, and EMI calculation." },
      { id: 6, title: "Agricultural & MSME Business Loans (Priority Sector)", category: "Core Subject", description: "Kisan Credit Cards (KCC), tractor loans, Mudra loans for small shops, and subsidy schemes." },
      { id: 7, title: "Finacle & Core Banking Solution (CBS) Software Lab", category: "Lab & Practical", description: "Operating bank branch software for cash deposits, account opening, RTGS/NEFT transfers." },
      { id: 8, title: "Non-Performing Assets (NPA) & Loan Recovery Law", category: "Core Subject", description: "Handling overdue loans, SARFAESI Act asset seizure, Lok Adalat recovery, and write-offs." },
      { id: 9, title: "Treasury Management & Foreign Exchange (Forex)", category: "Core Subject", description: "Currency exchange, Letter of Credit (LC), Bank Guarantee (BG), and export-import finance." },
      { id: 10, title: "Digital Banking & Cyber Fraud Prevention", category: "Lab & Practical", description: "UPI payment systems, debit card chargebacks, phishing prevention, and net banking security." },
      { id: 11, title: "Customer Relationship Management & Cross-Selling", category: "Core Subject", description: "Selling mutual funds, life insurance, fixed deposits, and resolving customer grievances." },
      { id: 12, title: "Financial Statement Analysis of Corporate Borrowers", category: "Lab & Practical", description: "Analyzing company balance sheets, debt-equity ratio, cash flows, and working capital limits." },
      { id: 13, title: "Bank Staff Training College Induction (3 Months)", category: "Advanced / Project", description: "Intensive residential training on branch operations, vault cash handling, and audits." },
      { id: 14, title: "2-Year Bank Branch Manager Probationary Posting", category: "Advanced / Project", description: "Hands-on branch rotation handling cash counters, loan verification, and branch accounts." },
    ],
  },
  {
    id: "mba",
    title: "Business Management (BBA / MBA)",
    shortCode: "MBA",
    icon: "💼",
    category: "Management",
    degreeTrack: "BBA (3 Years) or Any Degree + MBA (2 Years - IIM / Top B-Schools)",
    duration: "3 Years (BBA) / 2 Years (MBA)",
    eligibilityAfterInter: "10+2 (Any stream for BBA) or Any Degree + Entrance (CAT / MAT / GMAT)",
    oneLineSummary: "Learn business strategy, marketing campaigns, human resources, corporate finance, supply chain operations, and startup pitching.",
    topics: [
      { id: 1, title: "Principles of Management & Organizational Behavior", category: "Core Subject", description: "Leadership styles, team dynamics, workplace motivation, and corporate structures." },
      { id: 2, title: "Financial Accounting & Managerial Economics", category: "Core Subject", description: "Reading income statements, cost-volume-profit analysis, and market pricing strategies." },
      { id: 3, title: "Marketing Management & Consumer Psychology", category: "Core Subject", description: "4Ps of marketing, customer segmentation, product branding, and advertising strategies." },
      { id: 4, title: "Digital Marketing & Social Media Campaign Lab", category: "Lab & Practical", description: "Running Google Ads, SEO optimization, Facebook ad targeting, and email marketing funnels." },
      { id: 5, title: "Human Resource Management (HRM) & Talent Hiring", category: "Core Subject", description: "Recruiting employees, payroll processing, performance appraisals, and labor laws." },
      { id: 6, title: "Corporate Finance & Investment Valuation", category: "Core Subject", description: "Discounted Cash Flow (DCF), capital budgeting, stock equity valuation, and venture capital." },
      { id: 7, title: "Operations & Supply Chain Logistics Management", category: "Core Subject", description: "Warehouse inventory control, Six Sigma quality, logistics transport, and JIT manufacturing." },
      { id: 8, title: "Business Analytics & Advanced Excel / Power BI Lab", category: "Lab & Practical", description: "Building executive dashboards, sales forecasting, pivot tables, and statistical modeling." },
      { id: 9, title: "Strategic Management & Corporate Case Studies", category: "Core Subject", description: "Analyzing Harvard business case studies of Apple, Amazon, Tesla, and competitive strategy." },
      { id: 10, title: "International Business & Global Trade", category: "Core Subject", description: "Export-import policies, cross-cultural management, and foreign market entry strategies." },
      { id: 11, title: "Business Negotiation & Executive Pitching Lab", category: "Lab & Practical", description: "Simulated boardroom negotiations, client presentations, and startup elevator pitches." },
      { id: 12, title: "Entrepreneurship & Startup Business Plan Incubator", category: "Advanced / Project", description: "Drafting a complete viable startup business model, unit economics, and investor pitch deck." },
      { id: 13, title: "2-Month Paid Summer Corporate Internship", category: "Advanced / Project", description: "Working inside FMCG, consulting, banking, or tech corporate headquarters on live projects." },
      { id: 14, title: "Capstone Industry Consulting Project", category: "Advanced / Project", description: "Solving a real operational or market expansion problem for a partner corporate client." },
    ],
  },
  {
    id: "teacher",
    title: "Teacher / Lecturer",
    shortCode: "Teacher",
    icon: "👩‍🏫",
    category: "Education",
    degreeTrack: "B.A. / B.Sc. + B.Ed (Bachelor of Education) / D.Ed + TET / DSC",
    duration: "3-4 Years Degree + 2 Years B.Ed",
    eligibilityAfterInter: "Graduation in chosen subject (Maths / Science / Social / Languages) + B.Ed",
    oneLineSummary: "Master child educational psychology, blackboard teaching methods, lesson planning, student evaluation, and practical school teaching.",
    topics: [
      { id: 1, title: "Philosophical & Sociological Foundations of Education", category: "Core Subject", description: "Indian education thinkers (Gandhi, Tagore, Dewey), constitutional education values." },
      { id: 2, title: "Child Psychology & Cognitive Development", category: "Core Subject", description: "Piaget's learning stages, adolescent behavior, emotional intelligence, and memory retention." },
      { id: 3, title: "Pedagogy & Subject Teaching Methodology (Maths/Science/Social)", category: "Core Subject", description: "Specific scientific techniques to teach concepts simply, effectively, and engagingly." },
      { id: 4, title: "Lesson Planning & Teaching Learning Materials (TLM) Lab", category: "Lab & Practical", description: "Designing 45-minute lesson plans, building 3D charts, science models, and flashcards." },
      { id: 5, title: "Micro-Teaching Skills Practicum", category: "Lab & Practical", description: "Practicing blackboard handwriting, question posing, concept explanation, and reinforcement." },
      { id: 6, title: "Educational Technology & Smart Classroom Tools", category: "Lab & Practical", description: "Using interactive digital smart boards, educational PPTs, YouTube demos, and online quizzes." },
      { id: 7, title: "Assessment, Examination & Continuous Evaluation (CCE)", category: "Core Subject", description: "Creating balanced question papers, grading rubrics, diagnostic tests, and report cards." },
      { id: 8, title: "Inclusive Education & Special Needs Children", category: "Core Subject", description: "Teaching children with dyslexia, ADHD, physical challenges, and gifted children in regular classes." },
      { id: 9, title: "School Management, Assembly & Classroom Discipline", category: "Core Subject", description: "Managing 40-student classroom discipline, timetable preparation, and morning assemblies." },
      { id: 10, title: "Action Research & Solving Student Learning Difficulties", category: "Core Subject", description: "Conducting classroom research to diagnose why students struggle in maths/spelling." },
      { id: 11, title: "Guidance & Mental Wellbeing Counselling in Schools", category: "Core Subject", description: "Counselling students facing exam stress, bullying, family issues, and career confusion." },
      { id: 12, title: "Art, Music, Drama & Physical Education in Teaching", category: "Lab & Practical", description: "Conducting school cultural plays, sports events, science fairs, and morning yoga." },
      { id: 13, title: "16-Week Full-Time School Internship (Practice Teaching)", category: "Advanced / Project", description: "Teaching actual classes in government/private high schools under mentor supervision." },
      { id: 14, title: "State Teacher Eligibility Test (TET / DSC / CTET) Preparation", category: "Advanced / Project", description: "Mastering pedagogy exams for permanent government teacher appointments." },
    ],
  },
  {
    id: "pilot",
    title: "Commercial Pilot",
    shortCode: "Pilot",
    icon: "✈️",
    category: "Aviation",
    degreeTrack: "Commercial Pilot License (CPL - DGCA Approved Flying School)",
    duration: "18 to 24 Months (Ground School + 200 Flying Hours)",
    eligibilityAfterInter: "10+2 with Physics and Mathematics (50%+) + Class 1 DGCA Medical Fitness",
    oneLineSummary: "Study aircraft aerodynamics, cockpit flight instruments, weather meteorology, radio navigation, and complete 200 real flight hours.",
    topics: [
      { id: 1, title: "Principles of Flight & Aircraft Aerodynamics", category: "Core Subject", description: "Lift, drag, thrust, gravity, stall speeds, wing flaps, and flight control surfaces." },
      { id: 2, title: "Aviation Meteorology & Weather Radar", category: "Core Subject", description: "Cloud formations, thunderstorms, clear air turbulence, wind shear, and METAR weather reports." },
      { id: 3, title: "Air Navigation & GPS Route Planning", category: "Core Subject", description: "Latitude/longitude calculations, compass headings, wind drift correction, and flight computers." },
      { id: 4, title: "Aircraft Systems, Jet Engines & Instruments", category: "Core Subject", description: "Hydraulic systems, turbine engines, fuel pumps, altimeters, and artificial horizon gyros." },
      { id: 5, title: "Air Regulations & DGCA Aviation Law", category: "Core Subject", description: "Airspace classification (Class A-G), airport runway markings, right of way rules, and ICAO laws." },
      { id: 6, title: "Radio Telephony & Air Traffic Control (ATC) Communication", category: "Lab & Practical", description: "Speaking standard aviation English, runway takeoff clearances, and emergency Mayday calls." },
      { id: 7, title: "Pre-Flight Aircraft Physical Inspection", category: "Lab & Practical", description: "Checking fuel contamination, engine oil levels, tire pressures, and rudder movements on ramp." },
      { id: 8, title: "Single-Engine Flight Training (Cessna 172 / Piper Archer)", category: "Lab & Practical", description: "Takeoffs, level cruising, 45-degree steep turns, stalls, and smooth crosswind landings." },
      { id: 9, title: "Solo Flight & Cross-Country Flying (200 Hours)", category: "Lab & Practical", description: "Flying alone between cities across hundreds of nautical miles with navigational waypoints." },
      { id: 10, title: "Night Flying & Runway Lighting Operations", category: "Lab & Practical", description: "Takeoffs and landings in pitch darkness using runway approach lights and instrument guidance." },
      { id: 11, title: "Instrument Flying & Glass Cockpit Simulator Lab", category: "Lab & Practical", description: "Flying solely by looking at digital cockpit screens inside clouds and heavy rain simulators." },
      { id: 12, title: "Multi-Engine Aircraft Rating (Twin Engine)", category: "Lab & Practical", description: "Handling twin-propeller aircraft and emergency procedures when one engine fails in mid-air." },
      { id: 13, title: "Multi-Crew Cooperation & Crew Resource Management (CRM)", category: "Core Subject", description: "Captain and First Officer cockpit teamwork, sterile cockpit rules, and emergency checklists." },
      { id: 14, title: "Airline Type Rating (Airbus A320 / Boeing 737 Simulator)", category: "Advanced / Project", description: "Advanced full-flight Level-D simulator training before flying passenger airline jets." },
    ],
  },
  {
    id: "fashion",
    title: "Fashion Designer",
    shortCode: "Fashion Designer",
    icon: "👗",
    category: "Design & Arts",
    degreeTrack: "B.Des in Fashion Design (NIFT / Top Design Colleges)",
    duration: "4 Years (8 Semesters)",
    eligibilityAfterInter: "10+2 (Any stream) + NIFT / NID / UCEED Entrance",
    oneLineSummary: "Study fashion illustration, textile fabrics, pattern drafting, garment stitching, fashion styling, and organize runway fashion shows.",
    topics: [
      { id: 1, title: "Fashion Illustration & Figure Croquis Drawing", category: "Lab & Practical", description: "Drawing 10-head fashion body figures, hand-sketching dresses, and color rendering." },
      { id: 2, title: "Textile Science & Fabric Identification Lab", category: "Lab & Practical", description: "Testing cotton, silk, wool, synthetic fibers, weave patterns, yarn strength, and drape." },
      { id: 3, title: "Pattern Making & Flat Pattern Drafting Lab", category: "Lab & Practical", description: "Drafting basic paper patterns for bodices, skirts, collars, sleeves, and trousers with seam allowances." },
      { id: 4, title: "Garment Construction & Industrial Sewing Lab", category: "Lab & Practical", description: "Operating high-speed Juki sewing machines, stitching seams, zips, buttons, and linings." },
      { id: 5, title: "Fabric Dyeing, Printing & Surface Ornamentation Lab", category: "Lab & Practical", description: "Tie-and-dye, batik, block printing, screen printing, embroidery, and bead embellishments." },
      { id: 6, title: "Draping on Mannequin (Dress Form) Lab", category: "Lab & Practical", description: "Pinning and sculpting muslin fabric directly on dress form mannequins to create 3D silhouettes." },
      { id: 7, title: "History of World Costumes & Indian Heritage Textiles", category: "Core Subject", description: "Studying Victorian gowns, Mughal costumes, Banarasi silk, Kalamkari, and Ikat weaves." },
      { id: 8, title: "Digital Fashion Design (Adobe Illustrator & CLO 3D)", category: "Lab & Practical", description: "Creating digital technical flat drawings, moodboards, and 3D virtual garment simulations." },
      { id: 9, title: "Fashion Forecasting & Color Trend Analysis", category: "Core Subject", description: "Studying global trend books (WGSN, Pantone) to predict next season's popular colors and styles." },
      { id: 10, title: "Fashion Merchandising & Apparel Production Costing", category: "Core Subject", description: "Calculating fabric consumption, manufacturing costs, wholesale markups, and retail pricing." },
      { id: 11, title: "Fashion Styling, Photography & Visual Merchandising", category: "Lab & Practical", description: "Styling models for photo shoots, makeup coordination, and designing luxury store window displays." },
      { id: 12, title: "Sustainable & Eco-Friendly Circular Fashion", category: "Core Subject", description: "Zero-waste pattern cutting, organic cotton, natural herbal dyes, and upcycling old garments." },
      { id: 13, title: "2-Month Apparel Export House Internship", category: "Advanced / Project", description: "Working directly on assembly lines and sample design rooms of international clothing brands." },
      { id: 14, title: "Graduation Runway Fashion Collection (6 Outfits)", category: "Advanced / Project", description: "Designing, stitching, and presenting a complete 6-garment designer collection on live runway." },
    ],
  },
  {
    id: "designer",
    title: "Graphic Designer / UI-UX",
    shortCode: "Graphic Designer",
    icon: "🎨",
    category: "Design & Arts",
    degreeTrack: "B.Des in Visual Communication / UI-UX Design / Multimedia Diploma",
    duration: "3 to 4 Years",
    eligibilityAfterInter: "10+2 (Any stream)",
    oneLineSummary: "Master typography, brand logos, Photoshop editing, mobile app UI wireframing, user experience testing, and 3D visual motion.",
    topics: [
      { id: 1, title: "Design Fundamentals, Color Theory & Visual Balance", category: "Core Subject", description: "Color harmonies (RGB/CMYK), visual hierarchy, contrast, golden ratio, and composition rules." },
      { id: 2, title: "Typography & Font Pairings Lab", category: "Lab & Practical", description: "Studying serif, sans-serif fonts, kerning, leading, readability, and custom font lettering." },
      { id: 3, title: "Vector Illustration in Adobe Illustrator", category: "Lab & Practical", description: "Mastering pen tool, creating vector logos, custom icons, brand mascots, and print brochures." },
      { id: 4, title: "Photo Manipulation & Retouching in Adobe Photoshop", category: "Lab & Practical", description: "Layer masking, skin retouching, photo compositing, background removal, and color grading." },
      { id: 5, title: "Corporate Brand Identity & Brand Guideline Books", category: "Core Subject", description: "Designing complete logo systems, business cards, letterheads, and brand style guides." },
      { id: 6, title: "Editorial Design & Layouts in Adobe InDesign", category: "Lab & Practical", description: "Designing multi-page magazines, books, annual corporate reports, and print prepress files." },
      { id: 7, title: "UI-UX Design Principles & User Research", category: "Core Subject", description: "User personas, user journey mapping, pain point identification, and empathy interviews." },
      { id: 8, title: "Wireframing & Interactive Prototyping in Figma", category: "Lab & Practical", description: "Building clickable mobile app and web prototypes with animations and components in Figma." },
      { id: 9, title: "Usability Testing & User Experience Evaluation", category: "Lab & Practical", description: "Testing app designs with real users, tracking click drop-offs, and redesigning confusing UI." },
      { id: 10, title: "Motion Graphics & Social Video in Adobe After Effects", category: "Lab & Practical", description: "Creating animated logo reveals, kinetic typography, Instagram reels, and YouTube intros." },
      { id: 11, title: "Packaging Design & 3D Mockup Rendering", category: "Lab & Practical", description: "Designing product boxes, bottle labels, dielines, and rendering 3D photorealistic mockups." },
      { id: 12, title: "Basic Web Frontend (HTML/CSS & Webflow)", category: "Core Subject", description: "Understanding how visual designs get converted to web code using responsive grids and flexbox." },
      { id: 13, title: "Design Agency / Tech Startup Internship (3 Months)", category: "Advanced / Project", description: "Working as a visual design intern designing real marketing creatives and app features." },
      { id: 14, title: "Professional Behance & Dribbble Portfolio Showcase", category: "Advanced / Project", description: "Publishing 5 complete case studies showcasing end-to-end design problem solving." },
    ],
  },
  {
    id: "journalist",
    title: "Journalist / Media Reporter",
    shortCode: "Journalist",
    icon: "📰",
    category: "Media & Communication",
    degreeTrack: "B.A. in Journalism & Mass Communication (BJMC)",
    duration: "3 Years (6 Semesters)",
    eligibilityAfterInter: "10+2 (Any stream)",
    oneLineSummary: "Learn news reporting, interview techniques, live TV camera anchoring, digital news writing, video editing, and media ethics.",
    topics: [
      { id: 1, title: "News Reporting & Inverted Pyramid Writing", category: "Core Subject", description: "Writing news leads answering 5Ws and 1H (Who, What, When, Where, Why, How)." },
      { id: 2, title: "Investigative Journalism & Source Verification", category: "Core Subject", description: "Uncovering corruption, cross-checking official facts, protecting confidential sources, and RTI." },
      { id: 3, title: "Print Newsroom Copy Editing & Headline Crafting", category: "Lab & Practical", description: "Editing rough reporter drafts, fact-checking, writing punchy headlines, and news page layout." },
      { id: 4, title: "TV Studio News Anchoring & Teleprompter Lab", category: "Lab & Practical", description: "Reading teleprompters, voice modulation, posture, and conducting live studio debates." },
      { id: 5, title: "Video Camera Operations & Field Reporting", category: "Lab & Practical", description: "Operating professional video cameras, lapel mics, field audio, and conducting live street interviews." },
      { id: 6, title: "Video Editing in Premiere Pro & DaVinci Resolve", category: "Lab & Practical", description: "Cutting news packages, adding lower-third graphics, background voiceovers, and sound mixing." },
      { id: 7, title: "Digital & Mobile Journalism (MoJo)", category: "Lab & Practical", description: "Shooting, editing, and publishing breaking news stories entirely on smartphones for YouTube." },
      { id: 8, title: "Photojournalism & Action Photography Lab", category: "Lab & Practical", description: "Capturing storytelling moments, protests, sports events, and ethical photo curation." },
      { id: 9, title: "Media Laws, Defamation & Press Freedom", category: "Core Subject", description: "Article 19(1)(a) speech rights, libel, contempt of court, copyright laws, and Press Council codes." },
      { id: 10, title: "Political, Crime & Civic Affairs Beat Reporting", category: "Core Subject", description: "Covering election rallies, police crime press meets, municipal corporation meetings, and budgets." },
      { id: 11, title: "Podcast Production & Radio Broadcasting Lab", category: "Lab & Practical", description: "Recording radio news bulletins, hosting topical audio podcasts, and acoustic sound editing." },
      { id: 12, title: "Social Media Journalism, Fact-Checking & Fake News Busting", category: "Core Subject", description: "Using Google reverse image search and metadata tools to debunk viral social media misinformation." },
      { id: 13, title: "2-Month Live News Channel / Newspaper Internship", category: "Advanced / Project", description: "Working daily night and morning shifts on the assignment desk of a leading news organization." },
      { id: 14, title: "Independent 15-Minute Investigative Documentary", category: "Advanced / Project", description: "Researching, shooting, and editing a complete deep-dive video documentary on a public issue." },
    ],
  },
  {
    id: "architect",
    title: "Architect (B.Arch)",
    shortCode: "Architect",
    icon: "🏛️",
    category: "Architecture & Design",
    degreeTrack: "B.Arch (Bachelor of Architecture) - CoA Recognised",
    duration: "5 Years (10 Semesters)",
    eligibilityAfterInter: "Intermediate MPC (Physics & Mathematics compulsory, 45%+) + NATA or JEE Main Paper 2A",
    oneLineSummary: "Learn architectural drawing, spatial design, 3D BIM modeling, building materials, climate-responsive structures, and site coordination.",
    topics: [
      { id: 1, title: "Architectural Design Studio & Space Planning", category: "Core Subject", description: "Fundamental anthropometrics, spatial circulation, scale, proportion, and functional building layouts." },
      { id: 2, title: "Freehand Drawing & Visual Arts Lab", category: "Lab & Practical", description: "Perspective sketching, charcoal rendering, pencil shading, color theory, and composition aesthetics." },
      { id: 3, title: "Building Materials & Construction Technology Lab", category: "Lab & Practical", description: "Brickwork masonry, RCC foundations, timber joinery, glass, structural steel, and waterproofing." },
      { id: 4, title: "Architectural Graphics & 2D/3D CAD Lab", category: "Lab & Practical", description: "Drafting technical floor plans, cross-sections, elevation blueprints, and working drawings in AutoCAD." },
      { id: 5, title: "History of Architecture & Heritage Studies", category: "Core Subject", description: "Ancient Indian temple, Dravidian, Mughal, Greco-Roman, Renaissance, and contemporary architectural forms." },
      { id: 6, title: "Structural Mechanics & Theory of Structures", category: "Core Subject", description: "Load calculations, beams, columns, bending moments, trusses, and structural stability in buildings." },
      { id: 7, title: "Climate Responsive Architecture & Green Buildings", category: "Core Subject", description: "Sun-path diagrams, passive ventilation channels, daylighting, thermal insulation, and IGBC green ratings." },
      { id: 8, title: "3D Digital Modeling & Architectural Rendering Lab", category: "Lab & Practical", description: "Creating photorealistic 3D building visualisations and walkthroughs in Revit BIM, SketchUp, and Lumion." },
      { id: 9, title: "Building Services (Plumbing, Electrical & HVAC)", category: "Core Subject", description: "Sanitary plumbing networks, electrical circuits, fire protection systems, and central air conditioning." },
      { id: 10, title: "Landscape Architecture & Site Planning", category: "Lab & Practical", description: "Topographic contour analysis, exterior public plazas, drainage, gardens, and native plantation design." },
      { id: 11, title: "Urban Design, Housing & Town Planning", category: "Core Subject", description: "City master plans, zoning laws, FAR/FSI municipal bylaws, street design, and mass housing colonies." },
      { id: 12, title: "Architectural Professional Practice & Estimation", category: "Core Subject", description: "Drafting client contracts, Council of Architecture ethics, project tendering, cost estimation, and site checks." },
      { id: 13, title: "1-Semester Architectural Studio Practical Training", category: "Advanced / Project", description: "Full-time working internship inside a registered architectural design studio under a CoA architect." },
      { id: 14, title: "Final B.Arch Thesis & Capstone Design Project", category: "Advanced / Project", description: "Independent comprehensive design of a major institutional, medical, or civic building with 3D scale models." },
    ],
  },
  {
    id: "navy-airforce",
    title: "Indian Navy & Air Force Officer / Specialist",
    shortCode: "Navy & Air Force",
    icon: "⚓",
    category: "Armed Forces & Defense",
    degreeTrack: "B.Sc / B.Tech Cadet Degree + Naval / Air Force Academy Training",
    duration: "3-4 Years Academy Degree + 1-1.5 Years Specialist Pre-Commissioning Training",
    eligibilityAfterInter: "Intermediate MPC (Maths & Physics compulsory) + UPSC NDA & NA / Navy 10+2 B.Tech / AFCAT / CDS",
    oneLineSummary: "Train in military tactics, aircraft navigation, warship propulsion, radar electronics, weapon systems, and officer leadership.",
    topics: [
      { id: 1, title: "Military Leadership, Ethics & Armed Forces Law", category: "Core Subject", description: "Command hierarchy, military discipline, code of conduct, Geneva conventions, and tactical decision-making." },
      { id: 2, title: "Military Physical Training, Drills & Obstacle Courses", category: "Lab & Practical", description: "Daily 5km runs, battle obstacle assault courses, drill parade, rope climbing, and unarmed combat (UAC)." },
      { id: 3, title: "Small Arms Marksmanship & Weapons Handling", category: "Lab & Practical", description: "Firing range practice with INSAS rifles, pistols, LMGs, cleaning, safety protocols, and field strip drills." },
      { id: 4, title: "Terrestrial & Celestial Navigation (Navy) / Aerodynamics (Air Force)", category: "Core Subject", description: "Chart plotting, nautical compass reading, GPS systems, air traffic rules, and flight dynamics." },
      { id: 5, title: "Basic Aviation & Flight Simulator Training (Flying Branch)", category: "Lab & Practical", description: "Cockpit instrumentation, pre-flight checks, aerodynamic stall recovery, and basic trainer aircraft simulators." },
      { id: 6, title: "Marine Engineering, Ship Propulsion & Damage Control (Navy)", category: "Lab & Practical", description: "Marine diesel/gas turbine engines, hull inspection, fire fighting at sea, and flood containment drills." },
      { id: 7, title: "Radar, Avionics & Electronic Warfare Lab", category: "Lab & Practical", description: "Primary/secondary radar tracking, sonar acoustics, encrypted VHF/UHF tactical radio comms, and anti-jamming." },
      { id: 8, title: "Naval & Aerial Warfare Tactics", category: "Core Subject", description: "Fleet formations, anti-submarine warfare (ASW), missile defense vectors, combat air patrol (CAP), and escort missions." },
      { id: 9, title: "Sea Survival & Watermanship Training (Navy)", category: "Lab & Practical", description: "Open sea swimming, life raft deployment, helicopter winching, survival swimming, and emergency scuba diving." },
      { id: 10, title: "Meteorology & Flight Weather Analysis", category: "Core Subject", description: "Cloud formations, air turbulence, jet streams, monsoon wind vectors, and aviation flight weather advisories." },
      { id: 11, title: "Ground Defense, Air Base Security & Survival Skills", category: "Lab & Practical", description: "Jungle and desert survival, airfield camouflage, perimeter defense protocols, and counter-terror tactics." },
      { id: 12, title: "Military Logistics, Supply Chain & Armory Management", category: "Core Subject", description: "Munitions storage, aviation fuel (ATF) handling, spare parts supply lines, and warship replenishment at sea." },
      { id: 13, title: "On-Board Warship Sea Attachment / Air Force Squadron Attachment", category: "Advanced / Project", description: "3 to 6 months practical frontline attachment on active warships or operational fighter/transport airbases." },
      { id: 14, title: "Commissioning Passing-Out Parade (POP) & Officer Induction", category: "Advanced / Project", description: "Final ceremonial parade, receiving the President's Commission, officer stripes, and first squadron/ship posting." },
    ],
  },
  {
    id: "hotel-management",
    title: "Hotel Management & Hospitality",
    shortCode: "Hotel Management",
    icon: "🏨",
    category: "Hospitality & Tourism",
    degreeTrack: "B.Sc in Hospitality & Hotel Administration (NCHMCT / State University)",
    duration: "3 Years (6 Semesters)",
    eligibilityAfterInter: "10+2 Any Stream (MPC / BiPC / CEC / MEC) with English compulsory + NCHM JEE",
    oneLineSummary: "Master front office guest relations, food production & culinary arts, restaurant service, room housekeeping, and luxury resort operations.",
    topics: [
      { id: 1, title: "Food Production Fundamentals & Culinary Lab", category: "Lab & Practical", description: "Knife skills, culinary cutting styles, vegetable/meat cookery, stocks, soups, mother sauces, and kitchen hygiene." },
      { id: 2, title: "Food & Beverage (F&B) Service Operations Lab", category: "Lab & Practical", description: "Table layouts, French/American dining etiquette, napkin folding, order taking, and banquet service." },
      { id: 3, title: "Front Office Management & Hotel PMS Software Lab", category: "Lab & Practical", description: "Reservations, guest check-in/out, concierge services, keycard security, and Opera/IDS hotel software." },
      { id: 4, title: "Housekeeping & Accommodation Operations Lab", category: "Lab & Practical", description: "Room cleaning techniques, linen management, laundry equipment operations, flower arrangement, and maintenance." },
      { id: 5, title: "Regional Indian, Asian & Continental Cuisines", category: "Core Subject", description: "Cooking North Indian gravies, South Indian coastal dishes, Chinese wok cooking, and European pasta/baking." },
      { id: 6, title: "Bakery & Confectionery Practicals", category: "Lab & Practical", description: "Bread making, pastries, cakes, chocolate tempering, cookies, yeast fermentation, and dessert plating art." },
      { id: 7, title: "Bar Operations, Beverage Service & Mixology Lab", category: "Lab & Practical", description: "Mocktails, barista coffee brewing, glassware selection, tea varieties, and non-alcoholic beverage presentation." },
      { id: 8, title: "Hotel Accounting, Cost Control & Food Costing", category: "Core Subject", description: "Portion control, yield testing, banquet billing, daily revenue auditing, and restaurant profit margins." },
      { id: 9, title: "Food Safety, Nutrition & HACCP Hygiene Standards", category: "Core Subject", description: "Microbial food contamination, safe food storage temperatures, personal hygiene, and FSSAI standards." },
      { id: 10, title: "Facility Planning & Commercial Kitchen Design", category: "Core Subject", description: "Commercial kitchen ergonomics, restaurant layout drafting, ventilation hoods, waste disposal, and energy efficiency." },
      { id: 11, title: "Hospitality Sales, Marketing & Event / Banquet Management", category: "Core Subject", description: "Organizing corporate conferences, destination weddings, group bookings, and social media promotions." },
      { id: 12, title: "Human Resource Management & Guest Complaint Handling", category: "Core Subject", description: "Staff scheduling, service empathy, handling angry guests calmly, and service recovery protocols." },
      { id: 13, title: "20-Week Compulsory Industrial Exposure Training (IT)", category: "Advanced / Project", description: "Full 5-month paid rotating internship across all 4 departments inside a recognized 5-star luxury hotel." },
      { id: 14, title: "Final Year Hotel Simulation Project & Campus Placement", category: "Advanced / Project", description: "Running simulated fine-dining restaurant evenings, menu engineering presentations, and MT campus interviews." },
    ],
  },
  {
    id: "sports",
    title: "Sports / Professional Athlete & Coaching",
    shortCode: "Sports / Athlete",
    icon: "🏆",
    category: "Sports & Physical Education",
    degreeTrack: "Professional Sport League / SAI Academy Track or B.P.Ed / Sports Science",
    duration: "Ongoing Competitive Career (Youth through Senior Leagues)",
    eligibilityAfterInter: "10+2 Any stream + District/State/National sporting credentials or AP PECET for B.P.Ed",
    oneLineSummary: "Develop elite sport technique, strength conditioning, game tactical intelligence, injury rehabilitation, and tournament match performance.",
    topics: [
      { id: 1, title: "Sport-Specific Technical Skill Mastery", category: "Core Subject", description: "Daily repetition of specialized drills (batting/bowling in cricket, footwork/strokes in badminton, sprint mechanics)." },
      { id: 2, title: "Strength & Conditioning (S&C) Lab", category: "Lab & Practical", description: "Periodized gym resistance training, power lifting, core stability, agility ladders, and plyometric jump power." },
      { id: 3, title: "Speed, Stamina & Aerobic Endurance Training", category: "Lab & Practical", description: "High-Intensity Interval Training (HIIT), VO2 max testing, beep tests, shuttle runs, and track conditioning." },
      { id: 4, title: "Tactical Game Analysis & Match Strategy", category: "Core Subject", description: "Studying opponent game films, video tagging, positional positioning, set-pieces, and in-game tactical adjustments." },
      { id: 5, title: "Sports Nutrition, Hydration & Body Composition", category: "Core Subject", description: "Macro-nutrient timing, lean muscle mass maintenance, electrolyte replenishment, and anti-doping WADA compliance." },
      { id: 6, title: "Sports Psychology & Mental Toughness", category: "Core Subject", description: "Pre-performance routines, visualization, pressure penalty handling, managing performance anxiety, and focus drills." },
      { id: 7, title: "Injury Prevention, Physiotherapy & Sports Rehabilitation", category: "Lab & Practical", description: "Warm-up protocols, foam rolling, ice baths, hamstring/ACL strengthening, and sports tape strapping." },
      { id: 8, title: "Sports Biomechanics & Motion Capture Lab", category: "Lab & Practical", description: "High-speed video analysis of joint angles, body center of gravity, swing velocity, and movement efficiency." },
      { id: 9, title: "Tournament Match Competition & Federation Trials", category: "Lab & Practical", description: "Competing in district leagues, state championships, national federation trials, and Khelo India Games." },
      { id: 10, title: "Rules, Refereeing & Officiating Guidelines", category: "Core Subject", description: "In-depth knowledge of international sport federation rulebooks, penalty codes, and official scoring systems." },
      { id: 11, title: "Sports Science, Wearable Tech & GPS Tracking", category: "Lab & Practical", description: "Using GPS vests, heart rate monitors, and smart fitness trackers to monitor daily training load and fatigue." },
      { id: 12, title: "Media Training, Personal Branding & Sponsorships", category: "Core Subject", description: "Post-match interviews, professional athlete etiquette, social media engagement, and sports agent management." },
      { id: 13, title: "SAI National Centre of Excellence / High-Performance Academy Camp", category: "Advanced / Project", description: "Residential multi-week elite training camp under certified national and international coaches." },
      { id: 14, title: "National / International Championship Participation", category: "Advanced / Project", description: "Representing state, university, or nation in competitive tournaments, Ranji/IPL, or national games." },
    ],
  },
  {
    id: "govt-jobs",
    title: "Government Jobs (SSC / Railways / State Services)",
    shortCode: "Government Jobs",
    icon: "📋",
    category: "Public Administration",
    degreeTrack: "Any Graduation Degree (BA / B.Sc / B.Com / B.Tech) + Competitive Recruitment Exam",
    duration: "3-4 Years Degree + 6-18 Months Competitive Exam Preparation",
    eligibilityAfterInter: "10+2 (for SSC CHSL / RRB NTPC UG) or Any Bachelor's Degree (for SSC CGL / APPSC / RRB Graduate)",
    oneLineSummary: "Master quantitative aptitude, logical reasoning, general awareness, public administration procedures, and official government file documentation.",
    topics: [
      { id: 1, title: "Quantitative Aptitude & Arithmetic Reasoning", category: "Core Subject", description: "Percentages, ratios, profit & loss, simple/compound interest, time & work, algebra, and geometry." },
      { id: 2, title: "Logical & Analytical Reasoning Lab", category: "Lab & Practical", description: "Syllogisms, coding-decoding, blood relations, seating arrangements, puzzles, and non-verbal pattern recognition." },
      { id: 3, title: "General Awareness & Indian Polity (Constitution)", category: "Core Subject", description: "Fundamental rights, directive principles, Parliament functions, judiciary, and constitutional amendments." },
      { id: 4, title: "Indian History & National Movement", category: "Core Subject", description: "Ancient, medieval, modern Indian freedom struggle, socio-economic reforms, and post-independence history." },
      { id: 5, title: "Indian & World Geography", category: "Core Subject", description: "Physical landscapes, rivers, climate zones, agricultural patterns, mineral resources, and national transport corridors." },
      { id: 6, title: "Indian Economy & National Schemes", category: "Core Subject", description: "GDP growth, fiscal budget, RBI monetary policy, inflation, banking structure, and welfare social schemes (PM/State)." },
      { id: 7, title: "General Science & Technology in Everyday Life", category: "Core Subject", description: "Basic physics, chemistry, biology, human diseases, space missions (ISRO), and defence technology updates." },
      { id: 8, title: "English Comprehension, Grammar & Precise Writing", category: "Core Subject", description: "Reading comprehension passages, error spotting, vocabulary, idioms, sentence rearrangement, and letter drafting." },
      { id: 9, title: "Computer Literacy & Office Productivity Tools Lab", category: "Lab & Practical", description: "Windows OS, MS Word report typing, MS Excel formulas & sheets, MS PowerPoint, and internet security." },
      { id: 10, title: "State Specialization & Regional Governance (APPSC/State)", category: "Core Subject", description: "Andhra Pradesh geography, socio-economic history, bifurcation reorganization act, and state welfare initiatives." },
      { id: 11, title: "Data Interpretation (DI) & Statistical Charts", category: "Core Subject", description: "Pie charts, bar graphs, tabular data analysis, line graphs, and data sufficiency problem-solving." },
      { id: 12, title: "Public Administration, Citizen Grievance & RTI Act", category: "Core Subject", description: "Right to Information (RTI) procedures, citizen service charters, office file routing, and public accountability." },
      { id: 13, title: "Full-Length Online Mock Test Series & Time Management", category: "Advanced / Project", description: "Taking weekly simulated 100/200-question computer-based tests (CBT) with speed and negative-marking drills." },
      { id: 14, title: "Document Verification, Physical / Typing Test & Final Appointment", category: "Advanced / Project", description: "Clearing official document verification, regional typing/skill tests, and medical fitness check." },
    ],
  },
  {
    id: "scientist",
    title: "Scientist / Scientific Researcher",
    shortCode: "Scientist",
    icon: "🔬",
    category: "Pure & Applied Sciences",
    degreeTrack: "B.Sc / BS-MS (5 Yrs) ➔ M.Sc ➔ Ph.D (IISER / IISc / NISER / IIT)",
    duration: "5 Years (BS-MS) or 3+2 Years (B.Sc + M.Sc) + Ph.D Research",
    eligibilityAfterInter: "Intermediate MPC / BiPC / PCMB + IAT (IISER) / NEST / JEE Adv / IIT JAM",
    oneLineSummary: "Formulate research hypotheses, conduct laboratory experiments, analyze spectroscopic data, write scientific papers, and discover new technologies.",
    topics: [
      { id: 1, title: "Advanced Experimental Physics / Chemistry / Biology Lab", category: "Lab & Practical", description: "High-precision instrumentation, spectrophotometry, chromatography, and error analysis." },
      { id: 2, title: "Scientific Computing, Python & Numerical Methods Lab", category: "Lab & Practical", description: "Writing algorithms, differential equation solvers, Monte Carlo simulations, and scientific data plotting." },
      { id: 3, title: "Probability, Statistical Mechanics & Data Modeling", category: "Core Subject", description: "Hypothesis testing, p-values, regression analysis, distributions, and statistical thermodynamics." },
      { id: 4, title: "Molecular Spectroscopy, Crystallography & XRD", category: "Core Subject", description: "Analyzing molecular structure, crystal lattices, NMR spectroscopy, and mass spectrometry." },
      { id: 5, title: "Quantum Mechanics & Wave Optics (Physical Sciences)", category: "Core Subject", description: "Schrodinger wave equations, quantum states, laser physics, and semiconductor energy bands." },
      { id: 6, title: "Organic Synthesis & Reaction Mechanisms (Chemical Sciences)", category: "Core Subject", description: "Multi-step chemical synthesis, catalysts, green chemistry, and chromatography purification." },
      { id: 7, title: "Molecular Biology, Genetic Engineering & PCR Lab", category: "Lab & Practical", description: "DNA extraction, PCR gene amplification, gel electrophoresis, and CRISPR gene editing basics." },
      { id: 8, title: "Research Methodology, Literature Review & Paper Writing", category: "Core Subject", description: "Reading peer-reviewed journal papers (Nature/Science), citing prior art, and structuring papers." },
      { id: 9, title: "Materials Characterization & Electron Microscopy Lab (SEM/TEM)", category: "Lab & Practical", description: "Imaging materials at nanoscale, atomic force microscopy (AFM), and surface topography." },
      { id: 10, title: "Scientific Instrument Calibration & Cleanroom Protocols", category: "Lab & Practical", description: "Operating class-10,000 cleanrooms, vacuum pumps, cryogenics, and sensor calibration." },
      { id: 11, title: "Intellectual Property (IP), Patents & Research Ethics", category: "Core Subject", description: "Patent filing procedures, research integrity, laboratory biosafety levels (BSL-2/3), and ethics review." },
      { id: 12, title: "Research Grant Proposal & Scientific Presentation", category: "Core Subject", description: "Writing DST/SERB grant proposals, budget allocation, and presenting research posters at conferences." },
      { id: 13, title: "Major University / National Lab Summer Research Fellowship", category: "Advanced / Project", description: "2-3 month full-time fellowship at premier institutions (IISc, TIFR, CSIR, ISRO, or DRDO)." },
      { id: 14, title: "Final Master's / Doctoral Thesis Dissertation", category: "Advanced / Project", description: "Conducting original independent scientific research, defending thesis before an expert academic committee." },
    ],
  },
  {
    id: "entrepreneur",
    title: "Entrepreneur / Business Owner",
    shortCode: "Entrepreneur",
    icon: "🚀",
    category: "Business & Enterprise",
    degreeTrack: "Any Bachelor's Degree (BBA / B.Com / B.Tech) + Real-world Enterprise Incubation",
    duration: "Immediate Venture Building (Self-driven / Startup Incubators)",
    eligibilityAfterInter: "10+2 Any Stream (Commerce / MPC / BiPC / Humanities) - Customer validation is your qualification",
    oneLineSummary: "Discover market problems, develop Minimum Viable Products (MVP), acquire paying customers, manage cash flow, and scale profitable business operations.",
    topics: [
      { id: 1, title: "Opportunity Discovery, Market Research & Customer Empathy", category: "Core Subject", description: "Identifying market pain points, conducting customer interviews, and validating genuine willingness to pay." },
      { id: 2, title: "Minimum Viable Product (MVP) Prototyping Lab", category: "Lab & Practical", description: "Building rapid prototypes, landing pages, and no-code apps to test product concepts before spending capital." },
      { id: 3, title: "Business Model Canvas (BMC) & Value Proposition Design", category: "Core Subject", description: "Defining customer segments, cost structures, key revenue streams, and competitive moats." },
      { id: 4, title: "Financial Accounting, Cash Flow & Unit Economics", category: "Core Subject", description: "Tracking daily cash flow, Gross/Net profit margins, Customer Acquisition Cost (CAC), and Lifetime Value (LTV)." },
      { id: 5, title: "Sales Mastery, Cold Outreach & Deal Negotiation", category: "Core Subject", description: "Cold emailing, B2B sales pitches, handling customer objections, and closing high-value contracts." },
      { id: 6, title: "Digital Marketing, SEO & Social Media Growth", category: "Lab & Practical", description: "Content marketing, Google search SEO, performance ad campaigns (Meta/Google), and conversion rate optimization." },
      { id: 7, title: "Business Legal Structuring, GST & Regulatory Compliance", category: "Core Subject", description: "Registering MSME / Pvt Ltd entities, GST compliance, trademark filing, and commercial contract drafting." },
      { id: 8, title: "Product Manufacturing, Vendor Sourcing & Quality Control", category: "Core Subject", description: "Finding reliable component suppliers, raw material procurement, price negotiation, and production QA." },
      { id: 9, title: "Supply Chain Management & Inventory Operations", category: "Core Subject", description: "Warehouse storage logistics, delivery courier partnerships, stock turnover ratios, and returns management." },
      { id: 10, title: "Team Building, Recruitment & Organizational Culture", category: "Core Subject", description: "Writing job descriptions, conducting hiring interviews, delegating work, and creating incentive schemes." },
      { id: 11, title: "Customer Service, Retention & Review Management", category: "Core Subject", description: "Establishing quick customer support channels, tracking Net Promoter Score (NPS), and turning buyers into brand advocates." },
      { id: 12, title: "Working Capital Management & Banking Credit", category: "Core Subject", description: "Managing vendor credit terms, merchant payment gateways, bank loans (Mudra/CGTMSE), and managing receivables." },
      { id: 13, title: "Seed Funding, Investor Pitch Decks & Equity Term Sheets", category: "Advanced / Project", description: "Creating investor pitch decks, valuation basics, angel/VC fundraising, and cap table management." },
      { id: 14, title: "Multi-Unit Expansion & Scalable Growth Strategy", category: "Advanced / Project", description: "Replicating proven store/service models in new cities, franchising systems, and building operating SOPs." },
    ],
  },
  {
    id: "interior-designer",
    title: "Interior Designer (B.Des / B.Sc)",
    shortCode: "Interior Designer",
    icon: "🛋️",
    category: "Design & Spatial Arts",
    degreeTrack: "B.Des in Interior Design / B.Sc Interior & Spatial Design / 3-Year Diploma",
    duration: "3 to 4 Years (6-8 Semesters)",
    eligibilityAfterInter: "10+2 Any Stream (MPC / BiPC / CEC / MEC / Humanities) + Design Aptitude (NID DAT / College CET)",
    oneLineSummary: "Design functional and aesthetic interior layouts, select furniture, curate lighting, specify materials, and supervise on-site contractor execution.",
    topics: [
      { id: 1, title: "Interior Design Fundamentals, Anthropometrics & Space Planning", category: "Core Subject", description: "Human body dimensions, furniture clearances, traffic flow corridors, and room layout drafting." },
      { id: 2, title: "Freehand Sketching, Perspective & Color Palettes Lab", category: "Lab & Practical", description: "1-point and 2-point perspective drawing, rendering fabrics, wood textures, and psychological color harmony." },
      { id: 3, title: "2D Technical Drafting in AutoCAD Lab", category: "Lab & Practical", description: "Drafting floor plans, wall elevations, false ceiling blueprints, electrical points, and plumbing layout schematics." },
      { id: 4, title: "3D Spatial Modeling in SketchUp & 3ds Max", category: "Lab & Practical", description: "Building 3D room geometries, custom cabinetry, modular wardrobes, and parametric furniture objects." },
      { id: 5, title: "Photorealistic Rendering in V-Ray & Lumion Lab", category: "Lab & Practical", description: "Setting up artificial lighting, realistic sunlight angles, material bump maps, and generating high-res client renders." },
      { id: 6, title: "Interior Building Materials & Finishes", category: "Core Subject", description: "Plywood grades, laminates, natural veneers, acrylics, quartz countertops, Italian marble, and acoustic panels." },
      { id: 7, title: "Modular Kitchen & Custom Wardrobe Design", category: "Core Subject", description: "Ergonomic kitchen triangles, tandem drawers, hardware fittings (Hettich/Blum), and modular carcass design." },
      { id: 8, title: "Lighting Design, Fixtures & Electrical Coordination", category: "Core Subject", description: "Ambient, task, and accent lighting, lux levels, LED profiles, magnetic tracks, and switchboard positioning." },
      { id: 9, title: "False Ceiling & Acoustic Paneling Details", category: "Core Subject", description: "Gypsum board grids, POP moldings, cove lighting details, wooden rafters, and sound absorption materials." },
      { id: 10, title: "Soft Furnishings, Textiles & Styling Artistry", category: "Core Subject", description: "Upholstery fabrics, linen curtains, rugs, wall wallpapers, indoor planter curation, and art decor accessories." },
      { id: 11, title: "Quantity Surveying, Bill of Quantities (BOQ) & Estimating", category: "Core Subject", description: "Calculating square footage, carpentry rates, civil painting costs, and drafting client budget estimates." },
      { id: 12, title: "Contractor Supervision & Site Execution Management", category: "Core Subject", description: "Coordinating carpenters, electricians, plumbers, painters, and managing on-site quality inspection checklists." },
      { id: 13, title: "Full-Semester Interior Studio / Architecture Firm Internship", category: "Advanced / Project", description: "Working full-time inside an active interior design studio handling live residential and commercial client projects." },
      { id: 14, title: "Comprehensive Graduation Portfolio & Capstone Showcase", category: "Advanced / Project", description: "Executing and presenting an end-to-end luxury residence, restaurant, or co-working space design with full blueprints." },
    ],
  },
];

export const ALL_CAREER_CURRICULA = ALL_18_CAREER_CURRICULA;
